// Language translations for Emerald
const translations = {
    en: {
        title: "Emerald Chat",
        tagline: "Connect instantly with people around the world",
        subtitle: "Anonymous • Fast • Fun",
        download: "Download App",
        explore: "Explore Features",
        screenshot: "View Screenshot",
        loading: "Loading...",
        downloading: "Downloading: Emerald Chat...",
        downloadStarted: "Download started! Check your downloads folder.",
        downloadError: "Download failed. Please try again.",
        features: "Powerful Features",
        featuresSub: "Everything you need for amazing conversations",
        howItWorks: "How It Works",
        howItWorksSub: "Get started in 3 simple steps",
        safety: "Safety First",
        safetySub: "Your safety is our top priority",
        ready: "Ready to Meet Someone New?",
        readySub: "Join millions of users worldwide and start your conversation today",
        downloadLarge: "Download Emerald Chat",
        webVersion: "Use Web Version",
        apkSize: "APK • 10 MB",
        free: "Free to use",
        noRegistration: "No registration required",
        allDevices: "Works on all devices",
        safe: "Safe & secure",
        step1Title: "Download the App",
        step1Desc: "Click the download button to get the Emerald Chat APK file.",
        step2Title: "Install the APK",
        step2Desc: "Open the downloaded file and follow the installation prompts.",
        step3Title: "Open & Register",
        step3Desc: "Launch Emerald Chat, create your account, and start chatting!",
        proTip: "Pro Tip:",
        proTipDesc: "For easier installation, use a file manager app to locate and open the APK file.",
        compatible: "Compatible with Android 6.0 and above",
        visitSite: "Visit Website",
        faq: "FAQ",
        privacy: "Privacy Policy",
        footerNote: "This is a showcase page. Emerald Chat is a trademark of its respective owners.",
        madeBy: "The modern way to meet new people online"
    },
    ar: {
        title: "إيميرالد شات",
        tagline: "تواصل فوراً مع الناس من جميع أنحاء العالم",
        subtitle: "مجهول الهوية • سريع • ممتع",
        download: "تحميل التطبيق",
        explore: "استكشف المميزات",
        screenshot: "عرض لقطة الشاشة",
        loading: "جاري التحميل...",
        downloading: "جاري التنزيل: إيميرالد شات...",
        downloadStarted: "بدأ التنزيل! تحقق من مجلد التنزيلات.",
        downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
        features: "ميزات قوية",
        featuresSub: "كل ما تحتاجه للمحادثات المذهلة",
        howItWorks: "كيف يعمل",
        howItWorksSub: "ابدأ في 3 خطوات بسيطة",
        safety: "السلامة أولاً",
        safetySub: "سلامتك هي أولويتنا القصوى",
        ready: "مستعد للتعرف على شخص جديد؟",
        readySub: "انضم إلى ملايين المستخدمين حول العالم وابدأ محادثتك اليوم",
        downloadLarge: "تحميل إيميرالد شات",
        webVersion: "استخدم النسخة الويب",
        apkSize: "APK • 10 ميجابايت",
        free: "استخدام مجاني",
        noRegistration: "لا يتطلب التسجيل",
        allDevices: "يعمل على جميع الأجهزة",
        safe: "آمن ومحمي",
        step1Title: "تحميل التطبيق",
        step1Desc: "انقر على زر التنزيل للحصول على ملف تطبيق Emerald Chat.",
        step2Title: "تثبيت التطبيق",
        step2Desc: "افتح الملف الذي تم تنزيله واتبع تعليمات التثبيت.",
        step3Title: "افتح وسجّل",
        step3Desc: "أطلق إيميرالد شات، أنشئ حسابك، وابدأ الدردشة!",
        proTip: "نصيحة:",
        proTipDesc: "لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        compatible: "متوافق مع Android 6.0 وما فوق",
        visitSite: "زيارة الموقع",
        faq: "الأسئلة الشائعة",
        privacy: "سياسة الخصوصية",
        footerNote: "هذه صفحة عرض. Emerald Chat هو علامة تجارية مملوكة لأصحابها.",
        madeBy: "الطريقة الحديثة لمقابلة أشخاص جدد عبر الإنترنت"
    },
    es: {
        title: "Emerald Chat",
        tagline: "Conecta instantáneamente con personas de todo el mundo",
        subtitle: "Anónimo • Rápido • Divertido",
        download: "Descargar Aplicación",
        explore: "Explorar Características",
        screenshot: "Ver Captura",
        loading: "Cargando...",
        downloading: "Descargando: Emerald Chat...",
        downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
        downloadError: "Descarga fallida. Por favor, inténtalo de nuevo.",
        features: "Características Potentes",
        featuresSub: "Todo lo que necesitas para conversaciones increíbles",
        howItWorks: "Cómo Funciona",
        howItWorksSub: "Comienza en 3 simples pasos",
        safety: "Seguridad Primero",
        safetySub: "Tu seguridad es nuestra prioridad",
        ready: "¿Listo para Conocer a Alguien Nuevo?",
        readySub: "Únete a millones de usuarios en todo el mundo y comienza tu conversación hoy",
        downloadLarge: "Descargar Emerald Chat",
        webVersion: "Usar Versión Web",
        apkSize: "APK • 10 MB",
        free: "Gratis para usar",
        noRegistration: "Sin registro requerido",
        allDevices: "Funciona en todos los dispositivos",
        safe: "Seguro y protegido",
        step1Title: "Descarga la Aplicación",
        step1Desc: "Haz clic en el botón de descarga para obtener el archivo APK de Emerald Chat.",
        step2Title: "Instala el APK",
        step2Desc: "Abre el archivo descargado y sigue las instrucciones de instalación.",
        step3Title: "Abre y Regístrate",
        step3Desc: "Abre Emerald Chat, crea tu cuenta y comienza a chatear.",
        proTip: "Consejo Pro:",
        proTipDesc: "Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        compatible: "Compatible con Android 6.0 y superior",
        visitSite: "Visitar Sitio Web",
        faq: "Preguntas Frecuentes",
        privacy: "Política de Privacidad",
        footerNote: "Esta es una página de demostración. Emerald Chat es una marca comercial de sus respectivos propietarios.",
        madeBy: "La forma moderna de conocer personas nuevas en línea"
    },
    fr: {
        title: "Emerald Chat",
        tagline: "Connectez-vous instantanément avec des personnes du monde entier",
        subtitle: "Anonyme • Rapide • Amusant",
        download: "Télécharger l'Application",
        explore: "Explorer les Fonctionnalités",
        screenshot: "Voir Capture",
        loading: "Chargement...",
        downloading: "Téléchargement: Emerald Chat...",
        downloadStarted: "Téléchargement commencé! Vérifiez votre dossier de téléchargement.",
        downloadError: "Échec du téléchargement. Veuillez réessayer.",
        features: "Fonctionnalités Puissantes",
        featuresSub: "Tout ce dont vous avez besoin pour des conversations incroyables",
        howItWorks: "Comment Ça Marche",
        howItWorksSub: "Commencez en 3 étapes simples",
        safety: "Sécurité d'Abord",
        safetySub: "Votre sécurité est notre priorité absolue",
        ready: "Prêt à Rencontrer Quelqu'un de Nouveau?",
        readySub: "Rejoignez des millions d'utilisateurs dans le monde et commencez votre conversation aujourd'hui",
        downloadLarge: "Télécharger Emerald Chat",
        webVersion: "Version Web",
        apkSize: "APK • 10 Mo",
        free: "Gratuit à utiliser",
        noRegistration: "Aucune inscription requise",
        allDevices: "Fonctionne sur tous les appareils",
        safe: "Sûr et sécurisé",
        step1Title: "Télécharger l'Application",
        step1Desc: "Cliquez sur le bouton de téléchargement pour obtenir le fichier APK d'Emerald Chat.",
        step2Title: "Installer l'APK",
        step2Desc: "Ouvrez le fichier téléchargé et suivez les instructions d'installation.",
        step3Title: "Ouvrir et S'inscrire",
        step3Desc: "Lancez Emerald Chat, créez votre compte et commencez à discuter.",
        proTip: "Conseil Pro:",
        proTipDesc: "Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        compatible: "Compatible avec Android 6.0 et supérieur",
        visitSite: "Visiter le Site",
        faq: "FAQ",
        privacy: "Politique de Confidentialité",
        footerNote: "Ceci est une page de démonstration. Emerald Chat est une marque commerciale de ses propriétaires respectifs.",
        madeBy: "La façon moderne de rencontrer de nouvelles personnes en ligne"
    },
    de: {
        title: "Emerald Chat",
        tagline: "Verbinden Sie sich sofort mit Menschen auf der ganzen Welt",
        subtitle: "Anonym • Schnell • Spaß",
        download: "App Herunterladen",
        explore: "Funktionen Erkunden",
        screenshot: "Screenshot Anzeigen",
        loading: "Laden...",
        downloading: "Herunterladen: Emerald Chat...",
        downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
        downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
        features: "Leistungsstarke Funktionen",
        featuresSub: "Alles was Sie für unglaubliche Unterhaltungen brauchen",
        howItWorks: "So Funktionierts",
        howItWorksSub: "Starten Sie in 3 einfachen Schritten",
        safety: "Sicherheit Zuerst",
        safetySub: "Ihre Sicherheit ist unsere oberste Priorität",
        ready: "Bereit, Jemanden Neues Kennenzulernen?",
        readySub: "Schließen Sie sich Millionen von Benutzern weltweit an und beginnen Sie noch heute Ihr Gespräch",
        downloadLarge: "Emerald Chat Herunterladen",
        webVersion: "Web-Version Nutzen",
        apkSize: "APK • 10 MB",
        free: "Kostenlos Nutzen",
        noRegistration: "Keine Registrierung Erforderlich",
        allDevices: "Funktioniert Auf Allen Geräten",
        safe: "Sicher & Geschützt",
        step1Title: "App Herunterladen",
        step1Desc: "Klicken Sie auf den Download-Button, um die Emerald Chat APK-Datei zu erhalten.",
        step2Title: "APK Installieren",
        step2Desc: "Öffnen Sie die heruntergeladene Datei und folgen Sie den Installationsanweisungen.",
        step3Title: "Öffnen & Registrieren",
        step3Desc: "Starten Sie Emerald Chat, erstellen Sie Ihr Konto und fangen Sie an zu chatten.",
        proTip: "Pro-Tipp:",
        proTipDesc: "Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        compatible: "Kompatibel mit Android 6.0 und höher",
        visitSite: "Webseite Besuchen",
        faq: "FAQ",
        privacy: "Datenschutzerklärung",
        footerNote: "Dies ist eine Demo-Seite. Emerald Chat ist eine Marke der jeweiligen Eigentümer.",
        madeBy: "Die moderne Art, neue Leute online kennenzulernen"
    },
    zh: {
        title: "Emerald 聊天",
        tagline: "立即与世界各地的人联系",
        subtitle: "匿名 • 快速 • 有趣",
        download: "下载应用",
        explore: "探索功能",
        screenshot: "查看截图",
        loading: "加载中...",
        downloading: "正在下载: Emerald 聊天...",
        downloadStarted: "下载已开始！请检查您的下载文件夹。",
        downloadError: "下载失败。请重试。",
        features: "强大功能",
        featuresSub: "精彩对话所需的一切",
        howItWorks: "如何使用",
        howItWorksSub: "3 个简单步骤开始",
        safety: "安全第一",
        safetySub: "您的安全是我们的首要任务",
        ready: "准备认识新朋友了吗？",
        readySub: "加入全球数百万用户，立即开始对话",
        downloadLarge: "下载 Emerald 聊天",
        webVersion: "使用网页版",
        apkSize: "APK • 10 MB",
        free: "免费使用",
        noRegistration: "无需注册",
        allDevices: "适用于所有设备",
        safe: "安全可靠",
        step1Title: "下载应用",
        step1Desc: "点击下载按钮获取 Emerald 聊天 APK 文件。",
        step2Title: "安装 APK",
        step2Desc: "打开下载的文件并按照安装提示操作。",
        step3Title: "打开并注册",
        step3Desc: "启动 Emerald 聊天，创建账户，开始聊天！",
        proTip: "专业提示:",
        proTipDesc: "为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        compatible: "兼容 Android 6.0 及更高版本",
        visitSite: "访问网站",
        faq: "常见问题",
        privacy: "隐私政策",
        footerNote: "这是一个展示页面。Emerald 聊天是其各自所有者的商标。",
        madeBy: "在线结识新朋友的现代方式"
    },
    hi: {
        title: "Emerald चैट",
        tagline: "दुनिया भर के लोगों के साथ तुरंत जुड़ें",
        subtitle: "गुमनाम • तेज़ • मज़ेदार",
        download: "ऐप डाउनलोड करें",
        explore: "सुविधाएं देखें",
        screenshot: "स्क्रीनशॉट देखें",
        loading: "लोड हो रहा है...",
        downloading: "डाउनलोड हो रहा है: Emerald चैट...",
        downloadStarted: "डाउनलोड शुरू हो गया! अपने डाउनलोड फ़ोल्डर की जांच करें।",
        downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
        features: "शक्तिशाली सुविधाएं",
        featuresSub: "शानदार बातचीत के लिए आपको जो भी चाहिए",
        howItWorks: "यह कैसे काम करता है",
        howItWorksSub: "3 सरल चरणों में शुरू करें",
        safety: "सुरक्षा पहले",
        safetySub: "आपकी सुरक्षा हमारी शीर्ष प्राथमिकता है",
        ready: "किसी नए से मिलने के लिए तैयार हैं?",
        readySub: "दुनिया भर के लाखों उपयोगकर्ताओं से जुड़ें और आज अपनी बातचीत शुरू करें",
        downloadLarge: "Emerald चैट डाउनलोड करें",
        webVersion: "वेब संस्करण का प्रयोग करें",
        apkSize: "APK • 10 MB",
        free: "मुफ्त में उपयोग करें",
        noRegistration: "पंजीकरण की आवश्यकता नहीं",
        allDevices: "सभी उपकरणों पर काम करता है",
        safe: "सुरक्षित और सुरक्षित",
        step1Title: "ऐप डाउनलोड करें",
        step1Desc: "Emerald चैट APK फ़ाइल प्राप्त करने के लिए डाउनलोड बटन पर क्लिक करें।",
        step2Title: "APK इंस्टॉल करें",
        step2Desc: "डाउनलोड की गई फ़ाइल खोलें और इंस्टॉलेशन निर्देशों का पालन करें।",
        step3Title: "खोलें और पंजीकरण करें",
        step3Desc: "Emerald चैट लॉन्च करें, अपना खाता बनाएं और चैटिंग शुरू करें!",
        proTip: "प्रो टिप:",
        proTipDesc: "आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        compatible: "Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        visitSite: "वेबसाइट पर जाएं",
        faq: "अक्सर पूछे जाने वाले प्रश्न",
        privacy: "गोपनीयता नीति",
        footerNote: "यह एक प्रदर्शन पृष्ठ है। Emerald चैट अपने संबंधित मालिकों का एक ट्रेडमार्क है।",
        madeBy: "ऑनलाइन नए लोगों से मिलने का आधुनिक तरीका"
    },
    pt: {
        title: "Emerald Chat",
        tagline: "Conecte-se instantaneamente com pessoas ao redor do mundo",
        subtitle: "Anônimo • Rápido • Divertido",
        download: "Baixar Aplicativo",
        explore: "Explorar Recursos",
        screenshot: "Ver Captura",
        loading: "Carregando...",
        downloading: "Baixando: Emerald Chat...",
        downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
        downloadError: "Download falhou. Por favor, tente novamente.",
        features: "Recursos Poderosos",
        featuresSub: "Tudo o que você precisa para conversas incríveis",
        howItWorks: "Como Funciona",
        howItWorksSub: "Comece em 3 passos simples",
        safety: "Segurança em Primeiro Lugar",
        safetySub: "Sua segurança é nossa principal prioridade",
        ready: "Pronto para Conhecer Alguém Novo?",
        readySub: "Junte-se a milhões de usuários em todo o mundo e comece sua conversa hoje",
        downloadLarge: "Baixar Emerald Chat",
        webVersion: "Usar Versão Web",
        apkSize: "APK • 10 MB",
        free: "Gratuito para usar",
        noRegistration: "Sem registro necessário",
        allDevices: "Funciona em todos os dispositivos",
        safe: "Seguro e protegido",
        step1Title: "Baixe o Aplicativo",
        step1Desc: "Clique no botão de download para obter o arquivo APK do Emerald Chat.",
        step2Title: "Instale o APK",
        step2Desc: "Abra o arquivo baixado e siga as instruções de instalação.",
        step3Title: "Abra e Registre-se",
        step3Desc: "Abra o Emerald Chat, crie sua conta e comece a bater papo!",
        proTip: "Dica Pro:",
        proTipDesc: "Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        compatible: "Compatível com Android 6.0 e superior",
        visitSite: "Visitar Site",
        faq: "Perguntas Frequentes",
        privacy: "Política de Privacidade",
        footerNote: "Esta é uma página de demonstração. Emerald Chat é uma marca comercial de seus respectivos proprietários.",
        madeBy: "A forma moderna de conhecer novas pessoas online"
    }
};

// Language names in native script
const languageNames = {
    en: "English",
    ar: "العربية",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    zh: "中文",
    hi: "हिन्दी",
    pt: "Português"
};

// RTL languages
const rtlLanguages = ['ar'];
