// Language translations for Emerald
const translations = {
    en: {
        title: "Emerald Chat",
        tagline: "Connect instantly with people around the world",
        subtitle: "Anonymous • Fast • Fun",
        download: "Download App",
        explore: "Explore Features",
        screenshot: "View Screenshot",
        loading: "Loading...",
        downloading: "Downloading: Emerald Chat...",
        downloadStarted: "Download started! Check your downloads folder.",
        downloadError: "Download failed. Please try again.",
        features: "Powerful Features",
        featuresSub: "Everything you need for amazing conversations",
        howItWorks: "How It Works",
        howItWorksSub: "Get started in 3 simple steps",
        safety: "Safety First",
        safetySub: "Your safety is our top priority",
        ready: "Ready to Meet Someone New?",
        readySub: "Join millions of users worldwide and start your conversation today",
        downloadLarge: "Download Emerald Chat",
        webVersion: "Use Web Version",
        apkSize: "APK • 10 MB",
        free: "Free to use",
        noRegistration: "No registration required",
        allDevices: "Works on all devices",
        safe: "Safe & secure",
        step1Title: "Download the App",
        step1Desc: "Click the download button to get the Emerald Chat APK file.",
        step2Title: "Install the APK",
        step2Desc: "Open the downloaded file and follow the installation prompts.",
        step3Title: "Open & Register",
        step3Desc: "Launch Emerald Chat, create your account, and start chatting!",
        proTip: "Pro Tip:",
        proTipDesc: "For easier installation, use a file manager app to locate and open the APK file.",
        compatible: "Compatible with Android 6.0 and above",
        visitSite: "Visit Website",
        faq: "FAQ",
        privacy: "Privacy Policy",
        footerNote: "This is a showcase page. Emerald Chat is a trademark of its respective owners.",
        madeBy: "The modern way to meet new people online",
        statUsers: "Daily Users",
        statCountries: "Countries",
        statOnline: "Always Online",
        feat1Title: "Video Chat",
        feat1Desc: "High-quality video chats with strangers worldwide. Crystal clear audio and video for the best experience.",
        feat2Title: "Text Chat",
        feat2Desc: "Prefer typing? Text chat is always available with instant messaging and fun emojis.",
        feat3Title: "Interest Matching",
        feat3Desc: "Get matched with people who share your interests. More meaningful conversations await.",
        feat4Title: "Anonymous & Safe",
        feat4Desc: "Stay anonymous while chatting. Your privacy is protected with advanced security measures.",
        feat5Title: "Lightning Fast",
        feat5Desc: "Instant connections with minimal loading times. Start chatting in seconds, not minutes.",
        feat6Title: "Global Community",
        feat6Desc: "Connect with people from over 150 countries. Experience diverse cultures and perspectives.",
        feat7Title: "No Bots",
        feat7Desc: "Real people only. Advanced bot detection ensures you're chatting with genuine users.",
        feat8Title: "Customization",
        feat8Desc: "Personalize your experience with custom modes, filters, and chat preferences.",
        feat9Title: "Mobile Friendly",
        feat9Desc: "Works perfectly on all devices. Chat on your phone, tablet, or computer seamlessly.",
        feat10Title: "Fun Modes",
        feat10Desc: "Try different chat modes like random match, college chat, and more for varied experiences.",
        feat11Title: "Group Chat",
        feat11Desc: "Join group conversations and meet multiple people at once in themed chat rooms.",
        feat12Title: "Emerald Gold",
        feat12Desc: "Unlock premium features with Gold membership. Priority matching, exclusive badges, and more.",
        installTip: "💡 Pro Tip: For easier installation, use a file manager app to locate and open the APK file.",
        installCompat: "📱 Compatible with Android 6.0 and above",
        safety1: "Advanced moderation system",
        safety2: "Report inappropriate behavior",
        safety3: "Instant blocking of users",
        safety4: "Age verification requirements",
        safety5: "24/7 moderation team",
        safety6: "Community guidelines enforced",
        ctaNote1: "🌐 Free to use • No registration required",
        ctaNote2: "📱 Works on all devices • 🔒 Safe & secure",
        footerTitle: "Emerald Chat"
    },
    ar: {
        title: "إيميرالد شات",
        tagline: "تواصل فوراً مع الناس من جميع أنحاء العالم",
        subtitle: "مجهول الهوية • سريع • ممتع",
        download: "تحميل التطبيق",
        explore: "استكشف المميزات",
        screenshot: "عرض لقطة الشاشة",
        loading: "جاري التحميل...",
        downloading: "جاري التنزيل: إيميرالد شات...",
        downloadStarted: "بدأ التنزيل! تحقق من مجلد التنزيلات.",
        downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
        features: "ميزات قوية",
        featuresSub: "كل ما تحتاجه للمحادثات المذهلة",
        howItWorks: "كيف يعمل",
        howItWorksSub: "ابدأ في 3 خطوات بسيطة",
        safety: "السلامة أولاً",
        safetySub: "سلامتك هي أولويتنا القصوى",
        ready: "مستعد للتعرف على شخص جديد؟",
        readySub: "انضم إلى ملايين المستخدمين حول العالم وابدأ محادثتك اليوم",
        downloadLarge: "تحميل إيميرالد شات",
        webVersion: "استخدم النسخة الويب",
        apkSize: "APK • 10 ميجابايت",
        free: "استخدام مجاني",
        noRegistration: "لا يتطلب التسجيل",
        allDevices: "يعمل على جميع الأجهزة",
        safe: "آمن ومحمي",
        step1Title: "تحميل التطبيق",
        step1Desc: "انقر على زر التنزيل للحصول على ملف تطبيق Emerald Chat.",
        step2Title: "تثبيت التطبيق",
        step2Desc: "افتح الملف الذي تم تنزيله واتبع تعليمات التثبيت.",
        step3Title: "افتح وسجّل",
        step3Desc: "أطلق إيميرالد شات، أنشئ حسابك، وابدأ الدردشة!",
        proTip: "نصيحة:",
        proTipDesc: "لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        compatible: "متوافق مع Android 6.0 وما فوق",
        visitSite: "زيارة الموقع",
        faq: "الأسئلة الشائعة",
        privacy: "سياسة الخصوصية",
        footerNote: "هذه صفحة عرض. Emerald Chat هو علامة تجارية مملوكة لأصحابها.",
        madeBy: "الطريقة الحديثة لمقابلة أشخاص جدد عبر الإنترنت",
        statUsers: "المستخدمون اليوميون",
        statCountries: "الدول",
        statOnline: "متصل دائماً",
        feat1Title: "دردشة فيديو",
        feat1Desc: "محادثات فيديو عالية الجودة مع غرباء من جميع أنحاء العالم. صوت وصورة واضحة للتجربة الأفضل.",
        feat2Title: "دردشة نصية",
        feat2Desc: "تفضل الكتابة؟ الدردشة النصية متاحة دائماً مع مراسلة فورية ورموز تعبيرية ممتعة.",
        feat3Title: "مطابقة الاهتمامات",
        feat3Desc: "تواصل مع أشخاص يشاركونك اهتماماتك. محادثات أكثر معنى في انتظارك.",
        feat4Title: "مجهول وآمن",
        feat4Desc: "ابق مجهولاً أثناء الدردشة. خصوصيتك محمية بإجراءات أمنية متقدمة.",
        feat5Title: "سرعة البرق",
        feat5Desc: "اتصالات فورية بأوقات تحميل قليلة. ابدأ الدردشة في ثوانٍ، ليس دقائق.",
        feat6Title: "مجتمع عالمي",
        feat6Desc: "تواصل مع أشخاص من أكثر من 150 دولة. اختبر ثقافات وموجهات متنوعة.",
        feat7Title: "لا بوتات",
        feat7Desc: "أشخاص حقيقيون فقط. كشف البوت المتقدم يضمن أنك تتحدث مع مستخدمين حقيقيين.",
        feat8Title: "تخصيص",
        feat8Desc: "خصص تجربتك مع أوضاع مخصصة ومرشحات وتفضيلات الدردشة.",
        feat9Title: "متحرك الصديق",
        feat9Desc: "يعمل بشكل مثالي على جميع الأجهزة. تدردش على هاتفك أو جهازك اللوحي أو جهاز الكمبيوتر بسلاسة.",
        feat10Title: "أوضاع ممتعة",
        feat10Desc: "جرب أوضاع دردشة مختلفة مثل المطابقة العشوائية ودردشة الكلية والمزيد للتجارب المتنوعة.",
        feat11Title: "دردشة جماعية",
        feat11Desc: "انضم إلى محادثات جماعية وقابل عدة أشخاص في وقت واحد في غرف دردشة مواضيعية.",
        feat12Title: "إيميرالد الذهبي",
        feat12Desc: "افتح ميزات premium مع عضوية Gold. مطابقة الأولوية، شارات حصرية، والمزيد.",
        installTip: "💡 نصيحة: لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        installCompat: "📱 متوافق مع Android 6.0 وما فوق",
        safety1: "نظام إشراف متقدم",
        safety2: "الإبلاغ عن سلوك غير لائق",
        safety3: "حظر المستخدمين فوراً",
        safety4: "متطلبات التحقق من العمر",
        safety5: "فريق إشراف 24/7",
        safety6: "تطبيق إرشادات المجتمع",
        ctaNote1: "🌐 مجاني الاستخدام • لا يتطلب تسجيل",
        ctaNote2: "📱 يعمل على جميع الأجهزة • 🔒 آمن ومحمي",
        footerTitle: "إيميرالد شات"
    },
    es: {
        title: "Emerald Chat",
        tagline: "Conecta instantáneamente con personas de todo el mundo",
        subtitle: "Anónimo • Rápido • Divertido",
        download: "Descargar Aplicación",
        explore: "Explorar Características",
        screenshot: "Ver Captura",
        loading: "Cargando...",
        downloading: "Descargando: Emerald Chat...",
        downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
        downloadError: "Descarga fallida. Por favor, inténtalo de nuevo.",
        features: "Características Potentes",
        featuresSub: "Todo lo que necesitas para conversaciones increíbles",
        howItWorks: "Cómo Funciona",
        howItWorksSub: "Comienza en 3 simples pasos",
        safety: "Seguridad Primero",
        safetySub: "Tu seguridad es nuestra prioridad",
        ready: "¿Listo para Conocer a Alguien Nuevo?",
        readySub: "Únete a millones de usuarios en todo el mundo y comienza tu conversación hoy",
        downloadLarge: "Descargar Emerald Chat",
        webVersion: "Usar Versión Web",
        apkSize: "APK • 10 MB",
        free: "Gratis para usar",
        noRegistration: "Sin registro requerido",
        allDevices: "Funciona en todos los dispositivos",
        safe: "Seguro y protegido",
        step1Title: "Descarga la Aplicación",
        step1Desc: "Haz clic en el botón de descarga para obtener el archivo APK de Emerald Chat.",
        step2Title: "Instala el APK",
        step2Desc: "Abre el archivo descargado y sigue las instrucciones de instalación.",
        step3Title: "Abre y Regístrate",
        step3Desc: "Abre Emerald Chat, crea tu cuenta y comienza a chatear.",
        proTip: "Consejo Pro:",
        proTipDesc: "Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        compatible: "Compatible con Android 6.0 y superior",
        visitSite: "Visitar Sitio Web",
        faq: "Preguntas Frecuentes",
        privacy: "Política de Privacidad",
        footerNote: "Esta es una página de demostración. Emerald Chat es una marca comercial de sus respectivos propietarios.",
        madeBy: "La forma moderna de conocer personas nuevas en línea",
        statUsers: "Usuarios Diarios",
        statCountries: "Países",
        statOnline: "Siempre Online",
        feat1Title: "Chat de Video",
        feat1Desc: "Chats de video de alta calidad con extraños de todo el mundo. Audio y video cristalinos para la mejor experiencia.",
        feat2Title: "Chat de Texto",
        feat2Desc: "¿Prefieres escribir? El chat de texto siempre está disponible con mensajería instantánea y emojis divertidos.",
        feat3Title: "Coincidencia de Intereses",
        feat3Desc: "Conéctate con personas que comparten tus intereses. Conversaciones más significativas te esperan.",
        feat4Title: "Anónimo y Seguro",
        feat4Desc: "Mantente anonimato mientras chateas. Tu privacidad está protegida con medidas de seguridad avanzadas.",
        feat5Title: "Ultrarrápido",
        feat5Desc: "Conexiones instantáneas con tiempos de carga mínimos. Comienza a chatear en segundos, no minutos.",
        feat6Title: "Comunidad Global",
        feat6Desc: "Conéctate con personas de más de 150 países. Experimenta culturas diversas y perspectivas.",
        feat7Title: "Sin Bots",
        feat7Desc: "Solo personas reales. La detección avanzada de bots asegura que chateas con usuarios genuinos.",
        feat8Title: "Personalización",
        feat8Desc: "Personaliza tu experiencia con modos personalizados, filtros y preferencias de chat.",
        feat9Title: "Amigable con Móviles",
        feat9Desc: "Funciona perfectamente en todos los dispositivos. Chatea en tu teléfono, tableta o computadora sin problemas.",
        feat10Title: "Modos Divertidos",
        feat10Desc: "Prueba diferentes modos de chat como coincidencia aleatoria, chat universitario y más para experiencias variadas.",
        feat11Title: "Chat Grupal",
        feat11Desc: "Únete a conversaciones grupales y conoce a múltiples personas a la vez en salas de chat temáticas.",
        feat12Title: "Emerald Oro",
        feat12Desc: "Desbloquea características premium con membresía Gold. Coincidencia prioritaria, insignias exclusivas y más.",
        installTip: "💡 Consejo Pro: Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        installCompat: "📱 Compatible con Android 6.0 y superior",
        safety1: "Sistema de moderación avanzado",
        safety2: "Reportar comportamiento inapropiado",
        safety3: "Bloqueo instantáneo de usuarios",
        safety4: "Requisitos de verificación de edad",
        safety5: "Equipo de moderación 24/7",
        safety6: "Pautas de la comunidad aplicadas",
        ctaNote1: "🌐 Gratis para usar • Sin registro requerido",
        ctaNote2: "📱 Funciona en todos los dispositivos • 🔒 Seguro y protegido",
        footerTitle: "Emerald Chat"
    },
    fr: {
        title: "Emerald Chat",
        tagline: "Connectez-vous instantanément avec des personnes du monde entier",
        subtitle: "Anonyme • Rapide • Amusant",
        download: "Télécharger l'Application",
        explore: "Explorer les Fonctionnalités",
        screenshot: "Voir Capture",
        loading: "Chargement...",
        downloading: "Téléchargement: Emerald Chat...",
        downloadStarted: "Téléchargement commencé! Vérifiez votre dossier de téléchargement.",
        downloadError: "Échec du téléchargement. Veuillez réessayer.",
        features: "Fonctionnalités Puissantes",
        featuresSub: "Tout ce dont vous avez besoin pour des conversations incroyables",
        howItWorks: "Comment Ça Marche",
        howItWorksSub: "Commencez en 3 étapes simples",
        safety: "Sécurité d'Abord",
        safetySub: "Votre sécurité est notre priorité absolue",
        ready: "Prêt à Rencontrer Quelqu'un de Nouveau?",
        readySub: "Rejoignez des millions d'utilisateurs dans le monde et commencez votre conversation aujourd'hui",
        downloadLarge: "Télécharger Emerald Chat",
        webVersion: "Version Web",
        apkSize: "APK • 10 Mo",
        free: "Gratuit à utiliser",
        noRegistration: "Aucune inscription requise",
        allDevices: "Fonctionne sur tous les appareils",
        safe: "Sûr et sécurisé",
        step1Title: "Télécharger l'Application",
        step1Desc: "Cliquez sur le bouton de téléchargement pour obtenir le fichier APK d'Emerald Chat.",
        step2Title: "Installer l'APK",
        step2Desc: "Ouvrez le fichier téléchargé et suivez les instructions d'installation.",
        step3Title: "Ouvrir et S'inscrire",
        step3Desc: "Lancez Emerald Chat, créez votre compte et commencez à discuter.",
        proTip: "Conseil Pro:",
        proTipDesc: "Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        compatible: "Compatible avec Android 6.0 et supérieur",
        visitSite: "Visiter le Site",
        faq: "FAQ",
        privacy: "Politique de Confidentialité",
        footerNote: "Ceci est une page de démonstration. Emerald Chat est une marque commerciale de ses propriétaires respectifs.",
        madeBy: "La façon moderne de rencontrer de nouvelles personnes en ligne",
        statUsers: "Utilisateurs Quotidiens",
        statCountries: "Pays",
        statOnline: "Toujours en Ligne",
        feat1Title: "Chat Vidéo",
        feat1Desc: "Chats vidéo de haute qualité avec des inconnus du monde entier. Audio et vidéo cristallins pour la meilleure expérience.",
        feat2Title: "Chat Texte",
        feat2Desc: "Préférez-vous écrire? Le chat texte est toujours disponible avec messagerie instantanée et emojis amusants.",
        feat3Title: "Correspondance d'Intérêts",
        feat3Desc: "Soyez mis en relation avec des personnes qui partagent vos intérêts. Des conversations plus significatives vous attendent.",
        feat4Title: "Anonyme et Sûr",
        feat4Desc: "Restez anonyme tout en discutant. Votre confidentialité est protégée par des mesures de sécurité avancées.",
        feat5Title: "Ultra Rapide",
        feat5Desc: "Connexions instantanées avec des temps de chargement minimaux. Commencez à discuter en secondes, pas en minutes.",
        feat6Title: "Communauté Mondiale",
        feat6Desc: "Connectez-vous avec des personnes de plus de 150 pays. Découvrez des cultures et perspectives diverses.",
        feat7Title: "Pas de Bots",
        feat7Desc: "Que des vraies personnes. La détection avancée des bots assure que vous discutez avec de vrais utilisateurs.",
        feat8Title: "Personnalisation",
        feat8Desc: "Personnalisez votre expérience avec des modes personnalisés, des filtres et des préférences de chat.",
        feat9Title: "Compatible Mobile",
        feat9Desc: "Fonctionne parfaitement sur tous les appareils. Discutez sur votre téléphone, tablette ou ordinateur sans problème.",
        feat10Title: "Modes Amusants",
        feat10Desc: "Essayez différents modes de chat comme correspondance aléatoire, chat universitaire et plus pour des expériences variées.",
        feat11Title: "Chat de Groupe",
        feat11Desc: "Rejoignez des conversations de groupe et rencontrez plusieurs personnes à la fois dans des salons de chat thématiques.",
        feat12Title: "Emerald Or",
        feat12Desc: "Débloquez des fonctionnalités premium avec l'adhésion Gold. Correspondance prioritaire, badges exclusifs et plus.",
        installTip: "💡 Conseil Pro: Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        installCompat: "📱 Compatible avec Android 6.0 et supérieur",
        safety1: "Système de modération avancé",
        safety2: "Signaler un comportement inapproprié",
        safety3: "Blocage instantané des utilisateurs",
        safety4: "Exigences de vérification de l'âge",
        safety5: "Équipe de modération 24/7",
        safety6: "Directives de la communauté appliquées",
        ctaNote1: "🌐 Gratuit à utiliser • Aucune inscription requise",
        ctaNote2: "📱 Fonctionne sur tous les appareils • 🔒 Sûr et sécurisé",
        footerTitle: "Emerald Chat"
    },
    de: {
        title: "Emerald Chat",
        tagline: "Verbinden Sie sich sofort mit Menschen auf der ganzen Welt",
        subtitle: "Anonym • Schnell • Spaß",
        download: "App Herunterladen",
        explore: "Funktionen Erkunden",
        screenshot: "Screenshot Anzeigen",
        loading: "Laden...",
        downloading: "Herunterladen: Emerald Chat...",
        downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
        downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
        features: "Leistungsstarke Funktionen",
        featuresSub: "Alles was Sie für unglaubliche Unterhaltungen brauchen",
        howItWorks: "So Funktionierts",
        howItWorksSub: "Starten Sie in 3 einfachen Schritten",
        safety: "Sicherheit Zuerst",
        safetySub: "Ihre Sicherheit ist unsere oberste Priorität",
        ready: "Bereit, Jemanden Neues Kennenzulernen?",
        readySub: "Schließen Sie sich Millionen von Benutzern weltweit an und beginnen Sie noch heute Ihr Gespräch",
        downloadLarge: "Emerald Chat Herunterladen",
        webVersion: "Web-Version Nutzen",
        apkSize: "APK • 10 MB",
        free: "Kostenlos Nutzen",
        noRegistration: "Keine Registrierung Erforderlich",
        allDevices: "Funktioniert Auf Allen Geräten",
        safe: "Sicher & Geschützt",
        step1Title: "App Herunterladen",
        step1Desc: "Klicken Sie auf den Download-Button, um die Emerald Chat APK-Datei zu erhalten.",
        step2Title: "APK Installieren",
        step2Desc: "Öffnen Sie die heruntergeladene Datei und folgen Sie den Installationsanweisungen.",
        step3Title: "Öffnen & Registrieren",
        step3Desc: "Starten Sie Emerald Chat, erstellen Sie Ihr Konto und fangen Sie an zu chatten.",
        proTip: "Pro-Tipp:",
        proTipDesc: "Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        compatible: "Kompatibel mit Android 6.0 und höher",
        visitSite: "Webseite Besuchen",
        faq: "FAQ",
        privacy: "Datenschutzerklärung",
        footerNote: "Dies ist eine Demo-Seite. Emerald Chat ist eine Marke der jeweiligen Eigentümer.",
        madeBy: "Die moderne Art, neue Leute online kennenzulernen",
        statUsers: "Tägliche Benutzer",
        statCountries: "Länder",
        statOnline: "Immer Online",
        feat1Title: "Video-Chat",
        feat1Desc: "High-Quality-Video-Chats mit Fremden weltweit. Kristallklarer Audio und Video für das beste Erlebnis.",
        feat2Title: "Text-Chat",
        feat2Desc: "Schreiben bevorzugen? Text-Chat ist immer verfügbar mit Sofortnachrichten und lustigen Emojis.",
        feat3Title: "Interessen-basierte Vermittlung",
        feat3Desc: "Werden Sie mit Personen matched, die Ihre Interessen teilen. Bedeutungsvollere Gespräche warten.",
        feat4Title: "Anonym & Sicher",
        feat4Desc: "Bleiben Sie anonym beim Chatten. Ihre Privatsphäre ist mit fortschrittlichen Sicherheitsmaßnahmen geschützt.",
        feat5Title: "Blitzschnell",
        feat5Desc: "Sofortige Verbindungen mit minimalen Ladezeiten. Fangen Sie in Sekunden an zu chatten, nicht in Minuten.",
        feat6Title: "Globale Gemeinschaft",
        feat6Desc: "Verbinden Sie sich mit Personen aus über 150 Ländern. Erleben Sie diverse Kulturen und Perspektiven.",
        feat7Title: "Keine Bots",
        feat7Desc: "Nur echte Personen. Fortschrittliche Bot-Erkennung stellt sicher, dass Sie mit echten Benutzern chatten.",
        feat8Title: "Anpassung",
        feat8Desc: "Personalisieren Sie Ihr Erlebnis mit benutzerdefinierten Modi, Filtern und Chat-Präferenzen.",
        feat9Title: "Mobil-freundlich",
        feat9Desc: "Funktioniert perfekt auf allen Geräten. Chatten Sie nahtlos auf Ihrem Telefon, Tablet oder Computer.",
        feat10Title: "Spaßige Modi",
        feat10Desc: "Probieren Sie verschiedene Chat-Modi wie Zufallsmatch, College-Chat und mehr für variede Erlebnisse.",
        feat11Title: "Gruppen-Chat",
        feat11Desc: "Treten Sie Gruppengesprächen bei und treffen Sie mehrere Personen auf einmal in thematischen Chat-Räumen.",
        feat12Title: "Emerald Gold",
        feat12Desc: "Schalten Sie Premium-Funktionen mit Gold-Mitgliedschaft frei. Prioritäts-Matching, exklusive Abzeichen und mehr.",
        installTip: "💡 Pro-Tipp: Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        installCompat: "📱 Kompatibel mit Android 6.0 und höher",
        safety1: "Fortschrittliches Moderationssystem",
        safety2: "Unangemessenes Verhalten melden",
        safety3: "Sofortiges Blockieren von Benutzern",
        safety4: "Altersverifikationsanforderungen",
        safety5: "24/7-Moderationsteam",
        safety6: "Community-Richtlinien durchgesetzt",
        ctaNote1: "🌐 Kostenlos nutzen • Keine Registrierung erforderlich",
        ctaNote2: "📱 Funktioniert auf allen Geräten • 🔒 Sicher & geschützt",
        footerTitle: "Emerald Chat"
    },
    zh: {
        title: "Emerald 聊天",
        tagline: "立即与世界各地的人联系",
        subtitle: "匿名 • 快速 • 有趣",
        download: "下载应用",
        explore: "探索功能",
        screenshot: "查看截图",
        loading: "加载中...",
        downloading: "正在下载: Emerald 聊天...",
        downloadStarted: "下载已开始！请检查您的下载文件夹。",
        downloadError: "下载失败。请重试。",
        features: "强大功能",
        featuresSub: "精彩对话所需的一切",
        howItWorks: "如何使用",
        howItWorksSub: "3 个简单步骤开始",
        safety: "安全第一",
        safetySub: "您的安全是我们的首要任务",
        ready: "准备认识新朋友了吗？",
        readySub: "加入全球数百万用户，立即开始对话",
        downloadLarge: "下载 Emerald 聊天",
        webVersion: "使用网页版",
        apkSize: "APK • 10 MB",
        free: "免费使用",
        noRegistration: "无需注册",
        allDevices: "适用于所有设备",
        safe: "安全可靠",
        step1Title: "下载应用",
        step1Desc: "点击下载按钮获取 Emerald 聊天 APK 文件。",
        step2Title: "安装 APK",
        step2Desc: "打开下载的文件并按照安装提示操作。",
        step3Title: "打开并注册",
        step3Desc: "启动 Emerald 聊天，创建账户，开始聊天！",
        proTip: "专业提示:",
        proTipDesc: "为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        compatible: "兼容 Android 6.0 及更高版本",
        visitSite: "访问网站",
        faq: "常见问题",
        privacy: "隐私政策",
        footerNote: "这是一个展示页面。Emerald 聊天是其各自所有者的商标。",
        madeBy: "在线结识新朋友的现代方式",
        statUsers: "日活用户",
        statCountries: "国家",
        statOnline: "始终在线",
        feat1Title: "视频聊天",
        feat1Desc: "与全球陌生人进行高质量视频聊天。 crystal 清晰的音频和视频，带来最佳体验。",
        feat2Title: "文字聊天",
        feat2Desc: "更喜欢打字？文字聊天始终可用，支持即时消息和有趣的表情符号。",
        feat3Title: "兴趣匹配",
        feat3Desc: "与有相同兴趣的人匹配。更有意义的对话等待着你。",
        feat4Title: "匿名与安全",
        feat4Desc: "聊天时保持匿名。您的隐私受到先进安全措施的保护。",
        feat5Title: "闪电快速",
        feat5Desc: "即时连接，加载时间最短。几秒钟内开始聊天，而不是几分钟。",
        feat6Title: "全球社区",
        feat6Desc: "与来自150多个国家的人联系。体验多元文化和观点。",
        feat7Title: "无机器人",
        feat7Desc: "只有真人。先进的机器人检测确保您与真实用户聊天。",
        feat8Title: "自定义",
        feat8Desc: "通过自定义模式、过滤器和聊天偏好设置个性化您的体验。",
        feat9Title: "移动友好",
        feat9Desc: "在所有设备上完美运行。在手机、平板电脑或电脑上无缝聊天。",
        feat10Title: "有趣模式",
        feat10Desc: "尝试不同的聊天模式，如随机匹配、大学聊天等，获得多样化体验。",
        feat11Title: "群聊",
        feat11Desc: "加入群组对话，在主题聊天室中一次认识多个人。",
        feat12Title: "Emerald 金币",
        feat12Desc: "使用金会员解锁高级功能。优先匹配、专属徽章和更多。",
        installTip: "💡 专业提示：为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        installCompat: "📱 兼容 Android 6.0 及更高版本",
        safety1: "高级审核系统",
        safety2: "举报不当行为",
        safety3: "即时屏蔽用户",
        safety4: "年龄验证要求",
        safety5: "24/7 客服团队",
        safety6: "执行社区准则",
        ctaNote1: "🌐 免费使用 • 无需注册",
        ctaNote2: "📱 适用于所有设备 • 🔒 安全可靠",
        footerTitle: "Emerald 聊天"
    },
    hi: {
        title: "Emerald चैट",
        tagline: "दुनिया भर के लोगों के साथ तुरंत जुड़ें",
        subtitle: "गुमनाम • तेज़ • मज़ेदार",
        download: "ऐप डाउनलोड करें",
        explore: "सुविधाएं देखें",
        screenshot: "स्क्रीनशॉट देखें",
        loading: "लोड हो रहा है...",
        downloading: "डाउनलोड हो रहा है: Emerald चैट...",
        downloadStarted: "डाउनलोड शुरू हो गया! अपने डाउनलोड फ़ोल्डर की जांच करें।",
        downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
        features: "शक्तिशाली सुविधाएं",
        featuresSub: "शानदार बातचीत के लिए आपको जो भी चाहिए",
        howItWorks: "यह कैसे काम करता है",
        howItWorksSub: "3 सरल चरणों में शुरू करें",
        safety: "सुरक्षा पहले",
        safetySub: "आपकी सुरक्षा हमारी शीर्ष प्राथमिकता है",
        ready: "किसी नए से मिलने के लिए तैयार हैं?",
        readySub: "दुनिया भर के लाखों उपयोगकर्ताओं से जुड़ें और आज अपनी बातचीत शुरू करें",
        downloadLarge: "Emerald चैट डाउनलोड करें",
        webVersion: "वेब संस्करण का प्रयोग करें",
        apkSize: "APK • 10 MB",
        free: "मुफ्त में उपयोग करें",
        noRegistration: "पंजीकरण की आवश्यकता नहीं",
        allDevices: "सभी उपकरणों पर काम करता है",
        safe: "सुरक्षित और सुरक्षित",
        step1Title: "ऐप डाउनलोड करें",
        step1Desc: "Emerald चैट APK फ़ाइल प्राप्त करने के लिए डाउनलोड बटन पर क्लिक करें।",
        step2Title: "APK इंस्टॉल करें",
        step2Desc: "डाउनलोड की गई फ़ाइल खोलें और इंस्टॉलेशन निर्देशों का पालन करें।",
        step3Title: "खोलें और पंजीकरण करें",
        step3Desc: "Emerald चैट लॉन्च करें, अपना खाता बनाएं और चैटिंग शुरू करें!",
        proTip: "प्रो टिप:",
        proTipDesc: "आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        compatible: "Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        visitSite: "वेबसाइट पर जाएं",
        faq: "अक्सर पूछे जाने वाले प्रश्न",
        privacy: "गोपनीयता नीति",
        footerNote: "यह एक प्रदर्शन पृष्ठ है। Emerald चैट अपने संबंधित मालिकों का एक ट्रेडमार्क है।",
        madeBy: "ऑनलाइन नए लोगों से मिलने का आधुनिक तरीका",
        statUsers: "दैनिक उपयोगकर्ता",
        statCountries: "देश",
        statOnline: "हमेशा ऑनलाइन",
        feat1Title: "वीडियो चैट",
        feat1Desc: "दुनिया भर के अजनबियों के साथ हाई-क्वालिटी वीडियो चैट। सबसे अच्छे अनुभव के लिए क्रिस्टल-क्लियर ऑडियो और वीडियो।",
        feat2Title: "टेक्स्ट चैट",
        feat2Desc: "टाइपिंग पसंद है? टेक्स्ट चैट हमेशा इंस्टेंट मैसेजिंग और मजेदार इमोजी के साथ उपलब्ध है।",
        feat3Title: "ब्याज मिलान",
        feat3Desc: "अपने हितों को साझा करने वाले लोगों के साथ मिलान करें। अधिक सार्थक बातचीत का इंतजार है।",
        feat4Title: "गुमनाम और सुरक्षित",
        feat4Desc: "चैट करते समय गुमनाम रहें। आपकी गोपनीयता उन्नत सुरक्षा उपायों के साथ संरक्षित है।",
        feat5Title: "तेज़ रफ्तार",
        feat5Desc: "न्यूनतम लोडिंग समय के साथ त्वरित कनेक्शन। मिनटों में नहीं, सेकंड में चैटिंग शुरू करें।",
        feat6Title: "वैश्विक समुदाय",
        feat6Desc: "150 से अधिक देशों के लोगों के साथ जुड़ें। विविध संस्कृतियों और दृष्टिकोणों का अनुभव करें।",
        feat7Title: "कोई बॉट नहीं",
        feat7Desc: "केवल वास्तविक लोग। उन्नत बॉट पहचान सुनिश्चित करती है कि आप वास्तविक उपयोगकर्ताओं के साथ चैट कर रहे हैं।",
        feat8Title: "अनुकूलन",
        feat8Desc: "कस्टम मोड, फ़िल्टर और चैट प्राथमिकताओं के साथ अपने अनुभव को वैयक्तिकृत करें।",
        feat9Title: "मोबाइल के अनुकूल",
        feat9Desc: "सभी डिवाइस पर बेहतरीन ढंग से काम करता है। अपने फोन, टैबलेट या कंप्यूटर पर बिना किसी समस्या के चैट करें।",
        feat10Title: "मज़ेदार मोड",
        feat10Desc: "विविध अनुभवों के लिए रैंडम मैच, कॉलेज चैट और अधिक जैसे विभिन्न चैट मोड आज़माएं।",
        feat11Title: "समूह चैट",
        feat11Desc: "समूह वार्तालापों में शामिल हों और थीम वाल्ड चैट रूम में एक बार में कई लोगों से मिलें।",
        feat12Title: "Emerald गोल्ड",
        feat12Desc: "गोल्ड सदस्यता के साथ प्रीमियम सुविधाओं को अनलॉक करें। प्राथमिकता मिलान, विशेष बैज और बहुत कुछ।",
        installTip: "💡 प्रो टिप: आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        installCompat: "📱 Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        safety1: "उन्नत मॉडरेशन प्रणाली",
        safety2: "अनुचित व्यवहार की रिपोर्ट करें",
        safety3: "उपयोगकर्ताओं का तत्काल अवरोधन",
        safety4: "आयु सत्यापन आवश्यकताएं",
        safety5: "24/7 मॉडरेशन टीम",
        safety6: "सामुदायिक दिशानिर्देशों को लागू किया गया",
        ctaNote1: "🌐 मुफ्त में उपयोग करें • पंजीकरण की आवश्यकता नहीं",
        ctaNote2: "📱 सभी उपकरणों पर काम करता है • 🔒 सुरक्षित और सुरक्षित",
        footerTitle: "Emerald चैट"
    },
    pt: {
        title: "Emerald Chat",
        tagline: "Conecte-se instantaneamente com pessoas ao redor do mundo",
        subtitle: "Anônimo • Rápido • Divertido",
        download: "Baixar Aplicativo",
        explore: "Explorar Recursos",
        screenshot: "Ver Captura",
        loading: "Carregando...",
        downloading: "Baixando: Emerald Chat...",
        downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
        downloadError: "Download falhou. Por favor, tente novamente.",
        features: "Recursos Poderosos",
        featuresSub: "Tudo o que você precisa para conversas incríveis",
        howItWorks: "Como Funciona",
        howItWorksSub: "Comece em 3 passos simples",
        safety: "Segurança em Primeiro Lugar",
        safetySub: "Sua segurança é nossa principal prioridade",
        ready: "Pronto para Conhecer Alguém Novo?",
        readySub: "Junte-se a milhões de usuários em todo o mundo e comece sua conversa hoje",
        downloadLarge: "Baixar Emerald Chat",
        webVersion: "Usar Versão Web",
        apkSize: "APK • 10 MB",
        free: "Gratuito para usar",
        noRegistration: "Sem registro necessário",
        allDevices: "Funciona em todos os dispositivos",
        safe: "Seguro e protegido",
        step1Title: "Baixe o Aplicativo",
        step1Desc: "Clique no botão de download para obter o arquivo APK do Emerald Chat.",
        step2Title: "Instale o APK",
        step2Desc: "Abra o arquivo baixado e siga as instruções de instalação.",
        step3Title: "Abra e Registre-se",
        step3Desc: "Abra o Emerald Chat, crie sua conta e comece a bater papo!",
        proTip: "Dica Pro:",
        proTipDesc: "Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        compatible: "Compatível com Android 6.0 e superior",
        visitSite: "Visitar Site",
        faq: "Perguntas Frequentes",
        privacy: "Política de Privacidade",
        footerNote: "Esta é uma página de demonstração. Emerald Chat é uma marca comercial de seus respectivos proprietários.",
        madeBy: "A forma moderna de conhecer novas pessoas online",
        statUsers: "Usuários Diários",
        statCountries: "Países",
        statOnline: "Sempre Online",
        feat1Title: "Chat de Vídeo",
        feat1Desc: "Chats de vídeo de alta qualidade com estranhos em todo o mundo. Áudio e vídeo cristalinos para a melhor experiência.",
        feat2Title: "Chat de Texto",
        feat2Desc: "Prefere digitar? O chat de texto está sempre disponível com mensagens instantâneas e emojis divertidos.",
        feat3Title: "Correspondência de Interesses",
        feat3Desc: "Conecte-se com pessoas que compartilham seus interesses. Conversas mais significativas aguardam.",
        feat4Title: "Anônimo e Seguro",
        feat4Desc: "Mantenha-se anônimo enquanto conversa. Sua privacidade é protegida com medidas de segurança avançadas.",
        feat5Title: "Ultra Rápido",
        feat5Desc: "Conexões instantâneas com tempos de carregamento mínimos. Comece a conversar em segundos, não minutos.",
        feat6Title: "Comunidade Global",
        feat6Desc: "Conecte-se com pessoas de mais de 150 países. Experimente culturas diversas e perspectivas.",
        feat7Title: "Sem Bots",
        feat7Desc: "Apenas pessoas reais. A detecção avançada de bots garante que você está conversando com usuários genuínos.",
        feat8Title: "Personalização",
        feat8Desc: "Personalize sua experiência com modos personalizados, filtros e preferências de chat.",
        feat9Title: "Amigável para Mobile",
        feat9Desc: "Funciona perfeitamente em todos os dispositivos. Converse no seu telefone, tablet ou computador sem problemas.",
        feat10Title: "Modos Divertidos",
        feat10Desc: "Experimente diferentes modos de chat como correspondência aleatória, chat universitário e mais para experiências variadas.",
        feat11Title: "Chat em Grupo",
        feat11Desc: "Participe de conversas em grupo e conheça várias pessoas de uma vez em salas de chat temáticas.",
        feat12Title: "Emerald Gold",
        feat12Desc: "Desbloqueie recursos premium com associação Gold. Correspondência prioritária, distintivos exclusivos e mais.",
        installTip: "💡 Dica Pro: Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        installCompat: "📱 Compatível com Android 6.0 e superior",
        safety1: "Sistema de moderação avançado",
        safety2: "Relatar comportamento inadequado",
        safety3: "Bloqueio instantâneo de usuários",
        safety4: "Requisitos de verificação de idade",
        safety5: "Equipe de moderação 24/7",
        safety6: "Diretrizes da comunidade aplicadas",
        ctaNote1: "🌐 Gratuito para usar • Sem registro necessário",
        ctaNote2: "📱 Funciona em todos os dispositivos • 🔒 Seguro e protegido",
        footerTitle: "Emerald Chat"
    }
};

// Language names in native script
const languageNames = {
    en: "English",
    ar: "العربية",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    zh: "中文",
    hi: "हिन्दी",
    pt: "Português"
};

// RTL languages
const rtlLanguages = ['ar'];
