// Language translations for ChatterWave
const translations = {
    en: {
        title: "ChatterWave",
        tagline: "Simple. Fast. Private.",
        subtitle: "The messaging app that keeps it simple",
        download: "Download App",
        explore: "Explore Features",
        loading: "Loading...",
        downloading: "Downloading: ChatterWave...",
        downloadStarted: "Download started! Check your downloads folder.",
        downloadError: "Download failed. Please try again.",
        features: "Why ChatterWave?",
        featuresSub: "Everything you need, nothing you don't",
        howItWorks: "How It Works",
        howItWorksSub: "Get started in 3 simple steps",
        privacy: "Your Privacy Matters",
        privacySub: "We believe your conversations are your business",
        ready: "Ready to Simplify Your Messaging?",
        readySub: "Join thousands of people who've simplified their messaging experience",
        downloadLarge: "Download ChatterWave",
        step1Title: "Download the App",
        step1Desc: "Click the download button to get the ChatterWave APK file.",
        step2Title: "Install the APK",
        step2Desc: "Open the downloaded file and follow the installation prompts.",
        step3Title: "Create & Chat",
        step3Desc: "Pick a username, create a password, and start chatting instantly!",
        installTip: "💡 Pro Tip: For easier installation, use a file manager app to locate and open the APK file.",
        installCompat: "📱 Compatible with Android 6.0 and above",
        feat1Title: "Clean & Beautiful",
        feat1Desc: "Modern, distraction-free design that's easy on the eyes and simple to use.",
        feat2Title: "Share Anything",
        feat2Desc: "Send photos, videos, documents, and more. No limits on what you can share.",
        feat3Title: "Private Chats",
        feat3Desc: "Your conversations stay between you and the person you're talking to.",
        feat4Title: "Lightning Fast",
        feat4Desc: "Messages appear instantly. No waiting, no loading, just seamless chatting.",
        feat5Title: "Works Everywhere",
        feat5Desc: "Use it on your computer, tablet, or phone. Same great experience everywhere.",
        feat6Title: "Dark Mode",
        feat6Desc: "Automatically switches to dark mode at night. Easy on the eyes and battery.",
        feat7Title: "Chat History",
        feat7Desc: "Never lose a conversation. Your chats are automatically saved and organized.",
        feat8Title: "Secure",
        feat8Desc: "Your passwords are safely encrypted. Your privacy is our top priority.",
        feat9Title: "No Complicated Setup",
        feat9Desc: "Just username and password. You're done in 30 seconds. No phone verification needed.",
        privacy1: "Keeps your chats private - only you and your conversation partner can access them",
        privacy2: "Encrypts your password safely",
        privacy3: "Doesn't track your conversations",
        privacy4: "Doesn't sell your data",
        privacy5: "Respects your privacy",
        privacy6: "No ads, no distractions",
        ctaNote1: "🌐 No credit card required • No hidden fees",
        ctaNote2: "📱 Works on all devices • 🔒 Safe & secure",
        footerTitle: "ChatterWave",
        madeBy: "Simple messaging, real connections",
        footerNote: "Made with ❤️ for people who appreciate simplicity"
    },
    ar: {
        title: "تشاتر وييف",
        tagline: "بسيط. سريع. خاص.",
        subtitle: "تطبيق المراسلة الذي يحافظ على البساطة",
        download: "تحميل التطبيق",
        explore: "استكشف المميزات",
        loading: "جاري التحميل...",
        downloading: "جاري التنزيل: تشاتر وييف...",
        downloadStarted: "بدأ التنزيل! تحقق من مجلد التنزيلات.",
        downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
        features: "لماذا تشاتر وييف؟",
        featuresSub: "كل ما تحتاجه، لا شيء لا تحتاجه",
        howItWorks: "كيف يعمل",
        howItWorksSub: "ابدأ في 3 خطوات بسيطة",
        privacy: "خصوصيتك مهمة",
        privacySub: "نعتقد أن محادثاتك شأنك الخاص",
        ready: "مستعد لتبسيط مراسلاتك؟",
        readySub: "انضم إلى الآلاف من الأشخاص الذين بسطوا تجربة المراسلة",
        downloadLarge: "تحميل تشاتر وييف",
        step1Title: "تحميل التطبيق",
        step1Desc: "انقر على زر التنزيل للحصول على ملف تطبيق ChatterWave.",
        step2Title: "تثبيت التطبيق",
        step2Desc: "افتح الملف الذي تم تنزيله واتبع تعليمات التثبيت.",
        step3Title: "إنشاء والدردشة",
        step3Desc: "اختر اسم مستخدم، أنشئ كلمة مرور، وابدأ الدردشة فوراً!",
        installTip: "💡 نصيحة: لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        installCompat: "📱 متوافق مع Android 6.0 وما فوق",
        feat1Title: "نظيف وجميل",
        feat1Desc: "تصميم عصري خالٍ من التشتيت، مريح للعين وبسيط الاستخدام.",
        feat2Title: "شارك أي شيء",
        feat2Desc: "أرسل الصور ومقاطع الفيديو والمستندات والمزيد. لا حدود لما يمكنك مشاركته.",
        feat3Title: "دردشة خاصة",
        feat3Desc: "تبقى محادثاتك بينك وبين الشخص الذي تتحدث معه.",
        feat4Title: "سرعة البرق",
        feat4Desc: "تظهر الرسائل فوراً. لا انتظار، لا تحميل، فقط دردشة سلسة.",
        feat5Title: "يعمل في كل مكان",
        feat5Desc: "استخدمه على جهاز الكمبيوتر أو الجهاز اللوحي أو الهاتف. نفس التجربة الرائعة في كل مكان.",
        feat6Title: "الوضع الداكن",
        feat6Desc: "يتبديل تلقائياً إلى الوضع الداكن في الليل. مريح للعين والبطارية.",
        feat7Title: "سجل الدردشة",
        feat7Desc: "لا تفقد محادثة أبداً. يتم حفظ محادثاتك وتنظيمها تلقائياً.",
        feat8Title: "آمن",
        feat8Desc: "كلمات المرور الخاصة بك مشفرة بأمان. خصوصيتك هي أولويتنا القصوى.",
        feat9Title: "لا إعداد معقد",
        feat9Desc: "فقط اسم المستخدم وكلمة المرور. تنتهي في 30 ثانية. لا حاجة للتحقق من الهاتف.",
        privacy1: "يحافظ على خصوصية محادثاتك - فقط أنت وشريك محادثتك يمكنهما الوصول إليها",
        privacy2: "يشفّر كلمة المرور الخاصة بك بأمان",
        privacy3: "لا يتتبع محادثاتك",
        privacy4: "لا يبيع بياناتك",
        privacy5: "يحترم خصوصيتك",
        privacy6: "لا إعلانات، لا تشتيت",
        ctaNote1: "🌐 لا يتطلب بطاقة ائتمان • لا رسوم خفية",
        ctaNote2: "📱 يعمل على جميع الأجهزة • 🔒 آمن ومحمي",
        footerTitle: "تشاتر وييف",
        madeBy: "مراسلة بسيطة، روابط حقيقية",
        footerNote: "صنع بـ ❤️ للأشخاص الذين يقدرون البساطة"
    },
    es: {
        title: "ChatterWave",
        tagline: "Simple. Rápido. Privado.",
        subtitle: "La aplicación de mensajería que lo mantiene simple",
        download: "Descargar Aplicación",
        explore: "Explorar Características",
        loading: "Cargando...",
        downloading: "Descargando: ChatterWave...",
        downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
        downloadError: "Descarga fallida. Por favor, inténtalo de nuevo.",
        features: "¿Por qué ChatterWave?",
        featuresSub: "Todo lo que necesitas, nada que no",
        howItWorks: "Cómo Funciona",
        howItWorksSub: "Comienza en 3 simples pasos",
        privacy: "Tu Privacidad Importa",
        privacySub: "Creemos que tus conversaciones son tu negocio",
        ready: "¿Listo para Simplificar Tu Mensajería?",
        readySub: "Únete a miles de personas que han simplificado su experiencia de mensajería",
        downloadLarge: "Descargar ChatterWave",
        step1Title: "Descarga la Aplicación",
        step1Desc: "Haz clic en el botón de descarga para obtener el archivo APK de ChatterWave.",
        step2Title: "Instala el APK",
        step2Desc: "Abre el archivo descargado y sigue las instrucciones de instalación.",
        step3Title: "Crea y Chatea",
        step3Desc: "Elige un nombre de usuario, crea una contraseña y comienza a chatear al instante.",
        installTip: "💡 Consejo Pro: Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        installCompat: "📱 Compatible con Android 6.0 y superior",
        feat1Title: "Limpio y Hermoso",
        feat1Desc: "Diseño moderno sin distracciones, agradable a la vista y simple de usar.",
        feat2Title: "Comparte Todo",
        feat2Desc: "Envía fotos, videos, documentos y más. Sin límites en lo que puedes compartir.",
        feat3Title: "Chats Privados",
        feat3Desc: "Tus conversaciones se quedan entre tú y la persona con la que hablas.",
        feat4Title: "Ultrarrápido",
        feat4Desc: "Los mensajes aparecen al instante. Sin esperas, sin carga, solo chateo fluido.",
        feat5Title: "Funciona en Todas Partes",
        feat5Desc: "Úsalo en tu computadora, tablet o teléfono. La misma gran experiencia en todas partes.",
        feat6Title: "Modo Oscuro",
        feat6Desc: "Cambia automáticamente al modo oscuro por la noche. Fácil para los ojos y la batería.",
        feat7Title: "Historial de Chat",
        feat7Desc: "Nunca pierdas una conversación. Tus chats se guardan y organizan automáticamente.",
        feat8Title: "Seguro",
        feat8Desc: "Tus contraseñas están encriptadas de forma segura. Tu privacidad es nuestra máxima prioridad.",
        feat9Title: "Sin Configuración Complicada",
        feat9Desc: "Solo nombre de usuario y contraseña. Terminas en 30 segundos. No se necesita verificación de teléfono.",
        privacy1: "Mantiene tus chats privados - solo tú y tu compañero de chat pueden acceder a ellos",
        privacy2: "Encripta tu contraseña de forma segura",
        privacy3: "No rastrea tus conversaciones",
        privacy4: "No vende tus datos",
        privacy5: "Respeta tu privacidad",
        privacy6: "Sin anuncios, sin distracciones",
        ctaNote1: "🌐 No se requiere tarjeta de crédito • Sin tarifas ocultas",
        ctaNote2: "📱 Funciona en todos los dispositivos • 🔒 Seguro y protegido",
        footerTitle: "ChatterWave",
        madeBy: "Mensajería simple, conexiones reales",
        footerNote: "Hecho con ❤️ para personas que aprecian la simplicidad"
    },
    fr: {
        title: "ChatterWave",
        tagline: "Simple. Rapide. Privé.",
        subtitle: "L'application de messagerie qui reste simple",
        download: "Télécharger l'Application",
        explore: "Explorer les Fonctionnalités",
        loading: "Chargement...",
        downloading: "Téléchargement: ChatterWave...",
        downloadStarted: "Téléchargement commencé! Vérifiez votre dossier de téléchargement.",
        downloadError: "Échec du téléchargement. Veuillez réessayer.",
        features: "Pourquoi ChatterWave?",
        featuresSub: "Tout ce dont vous avez besoin, rien dont vous n'avez pas besoin",
        howItWorks: "Comment Ça Marche",
        howItWorksSub: "Commencez en 3 étapes simples",
        privacy: "Votre Confidentialité Compte",
        privacySub: "Nous croyons que vos conversations sont vos affaires",
        ready: "Prêt à Simplifier Vos Messages?",
        readySub: "Rejoignez des milliers de personnes qui ont simplifié leur expérience de messagerie",
        downloadLarge: "Télécharger ChatterWave",
        step1Title: "Télécharger l'Application",
        step1Desc: "Cliquez sur le bouton de téléchargement pour obtenir le fichier APK ChatterWave.",
        step2Title: "Installer l'APK",
        step2Desc: "Ouvrez le fichier téléchargé et suivez les instructions d'installation.",
        step3Title: "Créer et Chatter",
        step3Desc: "Choisissez un nom d'utilisateur, créez un mot de passe et commencez à chatter instantanément!",
        installTip: "💡 Conseil Pro: Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        installCompat: "📱 Compatible avec Android 6.0 et supérieur",
        feat1Title: "Propre et Beau",
        feat1Desc: "Design moderne sans distraction, agréable pour les yeux et simple à utiliser.",
        feat2Title: "Partagez Tout",
        feat2Desc: "Envoyez des photos, vidéos, documents et plus. Aucune limite sur ce que vous pouvez partager.",
        feat3Title: "Chats Privés",
        feat3Desc: "Vos conversations restent entre vous et la personne à qui vous parlez.",
        feat4Title: "Ultra Rapide",
        feat4Desc: "Les messages apparaissent instantanément. Pas d'attente, pas de chargement, juste des chats fluides.",
        feat5Title: "Fonctionne Partout",
        feat5Desc: "Utilisez-le sur votre ordinateur, tablette ou téléphone. La même excellente expérience partout.",
        feat6Title: "Mode Sombre",
        feat6Desc: "Passe automatiquement en mode sombre la nuit. Facile pour les yeux et la batterie.",
        feat7Title: "Historique de Chat",
        feat7Desc: "Ne perdez jamais une conversation. Vos chats sont automatiquement sauvegardés et organisés.",
        feat8Title: "Sécurisé",
        feat8Desc: "Vos mots de passe sont cryptés en toute sécurité. Votre confidentialité est notre priorité absolue.",
        feat9Title: "Pas de Configuration Compliquée",
        feat9Desc: "Juste nom d'utilisateur et mot de passe. Vous êtes prêt en 30 secondes. Pas besoin de vérification téléphonique.",
        privacy1: "Garde vos chats privés - seul vous et votre partenaire de chat pouvez y accéder",
        privacy2: "Crypte votre mot de passe en toute sécurité",
        privacy3: "Ne suit pas vos conversations",
        privacy4: "Ne vend pas vos données",
        privacy5: "Respecte votre vie privée",
        privacy6: "Pas de publicités, pas de distractions",
        ctaNote1: "🌐 Aucune carte de crédit requise • Aucuns frais cachés",
        ctaNote2: "📱 Fonctionne sur tous les appareils • 🔒 Sûr et sécurisé",
        footerTitle: "ChatterWave",
        madeBy: "Messagerie simple, connexions réelles",
        footerNote: "Fait avec ❤️ pour les gens qui apprécient la simplicité"
    },
    de: {
        title: "ChatterWave",
        tagline: "Einfach. Schnell. Privat.",
        subtitle: "Die Messenger-App, die einfach bleibt",
        download: "App Herunterladen",
        explore: "Funktionen Erkunden",
        loading: "Laden...",
        downloading: "Herunterladen: ChatterWave...",
        downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
        downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
        features: "Warum ChatterWave?",
        featuresSub: "Alles was Sie brauchen, nichts was Sie nicht brauchen",
        howItWorks: "So Funktionierts",
        howItWorksSub: "Starten Sie in 3 einfachen Schritten",
        privacy: "Ihre Privatsphäre ist Wichtig",
        privacySub: "Wir glauben, dass Ihre Gespräche Ihre Sache sind",
        ready: "Bereit, Ihre Nachrichten zu vereinfachen?",
        readySub: "Schließen Sie sich Tausenden von Menschen an, die ihre Messenger-Erfahrung vereinfacht haben",
        downloadLarge: "ChatterWave Herunterladen",
        step1Title: "App Herunterladen",
        step1Desc: "Klicken Sie auf den Download-Button, um die ChatterWave APK-Datei zu erhalten.",
        step2Title: "APK Installieren",
        step2Desc: "Öffnen Sie die heruntergeladene Datei und folgen Sie den Installationsanweisungen.",
        step3Title: "Erstellen & Chatten",
        step3Desc: "Wählen Sie einen Benutzernamen, erstellen Sie ein Passwort und fangen Sie sofort an zu chatten!",
        installTip: "💡 Pro-Tipp: Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        installCompat: "📱 Kompatibel mit Android 6.0 und höher",
        feat1Title: "Sauber & Schön",
        feat1Desc: "Modernes, ablenkungsfreies Design, das angenehm für die Augen und einfach zu verwenden ist.",
        feat2Title: "Alles Teilen",
        feat2Desc: "Senden Sie Fotos, Videos, Dokumente und mehr. Keine Grenzen für das, was Sie teilen können.",
        feat3Title: "Private Chats",
        feat3Desc: "Ihre Gespräche bleiben zwischen Ihnen und der Person, mit der Sie sprechen.",
        feat4Title: "Blitzschnell",
        feat4Desc: "Nachrichten erscheinen sofort. Kein Warten, kein Laden, nur nahtloses Chatten.",
        feat5Title: "Überall Funktionierend",
        feat5Desc: "Verwenden Sie es auf Ihrem Computer, Tablet oder Telefon. Die gleiche großartige Erfahrung überall.",
        feat6Title: "Dunkler Modus",
        feat6Desc: "Wechselt nachts automatisch in den dunklen Modus. Schont die Augen und den Akku.",
        feat7Title: "Chat-Verlauf",
        feat7Desc: "Verlieren Sie nie ein Gespräch. Ihre Chats werden automatisch gespeichert und organisiert.",
        feat8Title: "Sicher",
        feat8Desc: "Ihre Passwörter sind sicher verschlüsselt. Ihre Privatsphäre ist unsere oberste Priorität.",
        feat9Title: "Keine Komplizierte Einrichtung",
        feat9Desc: "Nur Benutzername und Passwort. Sie sind in 30 Sekunden fertig. Keine Telefonverifikation erforderlich.",
        privacy1: "Behält Ihre Chats privat - nur Sie und Ihr Chat-Partner können darauf zugreifen",
        privacy2: "Verschlüsselt Ihr Passwort sicher",
        privacy3: "Verfolgt Ihre Gespräche nicht",
        privacy4: "Verkauft Ihre Daten nicht",
        privacy5: "Respektiert Ihre Privatsphäre",
        privacy6: "Keine Werbung, keine Ablenkungen",
        ctaNote1: "🌐 Keine Kreditkarte erforderlich • Keine versteckten Gebühren",
        ctaNote2: "📱 Funktioniert auf allen Geräten • 🔒 Sicher & geschützt",
        footerTitle: "ChatterWave",
        madeBy: "Einfache Nachrichten, echte Verbindungen",
        footerNote: "Gemacht mit ❤️ für Menschen, die Einfachheit zu schätzen wissen"
    },
    zh: {
        title: "ChatterWave",
        tagline: "简单。快速。私密。",
        subtitle: "保持简单的消息应用",
        download: "下载应用",
        explore: "探索功能",
        loading: "加载中...",
        downloading: "正在下载: ChatterWave...",
        downloadStarted: "下载已开始！请检查您的下载文件夹。",
        downloadError: "下载失败。请重试。",
        features: "为什么选择 ChatterWave?",
        featuresSub: "您需要的，没有您不需要的",
        howItWorks: "如何使用",
        howItWorksSub: "3 个简单步骤开始",
        privacy: "您的隐私很重要",
        privacySub: "我们相信您的对话是您的事",
        ready: "准备好简化您的消息了吗？",
        readySub: "加入成千上万简化消息体验的人",
        downloadLarge: "下载 ChatterWave",
        step1Title: "下载应用",
        step1Desc: "点击下载按钮获取 ChatterWave APK 文件。",
        step2Title: "安装 APK",
        step2Desc: "打开下载的文件并按照安装提示操作。",
        step3Title: "创建和聊天",
        step3Desc: "选择用户名，创建密码，立即开始聊天！",
        installTip: "💡 专业提示：为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        installCompat: "📱 兼容 Android 6.0 及更高版本",
        feat1Title: "干净美观",
        feat1Desc: "现代、无干扰的设计，易于眼睛且易于使用。",
        feat2Title: "分享任何内容",
        feat2Desc: "发送照片、视频、文档等。对您可以分享的内容没有限制。",
        feat3Title: "私密聊天",
        feat3Desc: "您的对话仅保留在您和您交谈的人之间。",
        feat4Title: "闪电快速",
        feat4Desc: "消息瞬间出现。无需等待，无需加载，只需无缝聊天。",
        feat5Title: "随处可用",
        feat5Desc: "在电脑、平板电脑或手机上使用。在任何地方都有同样出色的体验。",
        feat6Title: "深色模式",
        feat6Desc: "夜间自动切换到深色模式。对眼睛和电池都很友好。",
        feat7Title: "聊天记录",
        feat7Desc: "永不丢失对话。您的聊天记录会自动保存和组织。",
        feat8Title: "安全",
        feat8Desc: "您的密码经过安全加密。您的隐私是我们的首要任务。",
        feat9Title: "没有复杂的设置",
        feat9Desc: "只需用户名和密码。30秒内完成。无需电话验证。",
        privacy1: "保持您的聊天私密 - 只有您和您的聊天伙伴可以访问",
        privacy2: "安全加密您的密码",
        privacy3: "不跟踪您的对话",
        privacy4: "不出售您的数据",
        privacy5: "尊重您的隐私",
        privacy6: "没有广告，没有干扰",
        ctaNote1: "🌐 不需要信用卡 • 没有隐藏费用",
        ctaNote2: "📱 适用于所有设备 • 🔒 安全可靠",
        footerTitle: "ChatterWave",
        madeBy: "简单的消息传递，真实的连接",
        footerNote: "用 ❤️ 为那些欣赏简单的人制作"
    },
    hi: {
        title: "ChatterWave",
        tagline: "सरल। तेज़। निजी।",
        subtitle: "मैसेजिंग ऐप जो सरल रखती है",
        download: "ऐप डाउनलोड करें",
        explore: "सुविधाएं देखें",
        loading: "लोड हो रहा है...",
        downloading: "डाउनलोड हो रहा है: ChatterWave...",
        downloadStarted: "डाउनलोड शुरू हो गया! अपने डाउनलोड फ़ोल्डर की जांच करें।",
        downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
        features: "ChatterWave क्यों?",
        featuresSub: "जो आपको चाहिए, वही सब कुछ",
        howItWorks: "यह कैसे काम करता है",
        howItWorksSub: "3 सरल चरणों में शुरू करें",
        privacy: "आपकी गोपनीयता मायने रखती है",
        privacySub: "हम मानते हैं कि आपकी बातचीत आपका व्यवसाय है",
        ready: "अपनी मैसेजिंग को सरल करने के लिए तैयार हैं?",
        readySub: "हजारों लोगों से जुड़ें जिन्होंने अपनी मैसेजिंग अनुभव को सरल किया है",
        downloadLarge: "ChatterWave डाउनलोड करें",
        step1Title: "ऐप डाउनलोड करें",
        step1Desc: "ChatterWave APK फ़ाइल प्राप्त करने के लिए डाउनलोड बटन पर क्लिक करें।",
        step2Title: "APK इंस्टॉल करें",
        step2Desc: "डाउनलोड की गई फ़ाइल खोलें और इंस्टॉलेशन निर्देशों का पालन करें।",
        step3Title: "बनाएं और चैट करें",
        step3Desc: "एक उपयोगकर्ता नाम चुनें, पासवर्ड बनाएं, और तुरंत चैटिंग शुरू करें!",
        installTip: "💡 प्रो टिप: आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        installCompat: "📱 Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        feat1Title: "साफ और सुंदर",
        feat1Desc: "आधुनिक, विनाशकारी मुक्त डिज़ाइन जो आंखों के लिए आरामदायक और उपयोग करने में आसान है।",
        feat2Title: "कुछ भी साझा करें",
        feat2Desc: "फ़ोटो, वीडियो, दस्तावेज़ और बहुत कुछ भेजें। आप जो साझा कर सकते हैं उसकी कोई सीमा नहीं।",
        feat3Title: "निजी चैट",
        feat3Desc: "आपकी बातचीत आप और जिससे आप बात कर रहे हैं उसके बीच रहती है।",
        feat4Title: "तेज़ रफ़्तार",
        feat4Desc: "संदेश तुरंत दिखाई देते हैं। कोई प्रतीक्षा नहीं, कोई लोडिंग नहीं, बस बेहतरीन चैटिंग।",
        feat5Title: "हर जगह काम करता है",
        feat5Desc: "इसे अपने कंप्यूटर, टैबलेट या फ़ोन पर उपयोग करें। हर जगह वही शानदार अनुभव।",
        feat6Title: "डार्क मोड",
        feat6Desc: "रात में स्वचालित रूप से डार्क मोड में बदल जाता है। आंखों और बैटरी के लिए आसान।",
        feat7Title: "चैट इतिहास",
        feat7Desc: "कभी बातचीत न खोएं। आपकी चैट स्वचालित रूप से सहेजी और व्यवस्थित होती हैं।",
        feat8Title: "सुरक्षित",
        feat8Desc: "आपके पासवर्ड सुरक्षित रूप से एन्क्रिप्ट किए जाते हैं। आपकी गोपनीयता हमारी शीर्ष प्राथमिकता है।",
        feat9Title: "कोई जटिल सेटअप नहीं",
        feat9Desc: "बस उपयोगकर्ता नाम और पासवर्ड। 30 सेकंड में हो जाएं। फ़ोन सत्यापन की आवश्यकता नहीं।",
        privacy1: "आपकी चैट को निजी रखता है - केवल आप और आपके चैट साथी ही उस तक पहुंच सकते हैं",
        privacy2: "आपके पासवर्ड को सुरक्षित रूप से एन्क्रिप्ट करता है",
        privacy3: "आपकी बातचीत को ट्रैक नहीं करता",
        privacy4: "आपका डेटा नहीं बेचता",
        privacy5: "आपकी गोपनीयता का सम्मान करता है",
        privacy6: "कोई विज्ञापन नहीं, कोई विघात नहीं",
        ctaNote1: "🌐 कोई क्रेडिट कार्ड की आवश्यकता नहीं • कोई छिपी फीस नहीं",
        ctaNote2: "📱 सभी डिवाइस पर काम करता है • 🔒 सुरक्षित और सुरक्षित",
        footerTitle: "ChatterWave",
        madeBy: "सरल संदेश, वास्तविक कनेक्शन",
        footerNote: "सरलता की सराहना करने वाले लोगों के लिए ❤️ के साथ बनाया गया"
    },
    pt: {
        title: "ChatterWave",
        tagline: "Simples. Rápido. Privado.",
        subtitle: "O aplicativo de mensagens que mantém simples",
        download: "Baixar Aplicativo",
        explore: "Explorar Recursos",
        loading: "Carregando...",
        downloading: "Baixando: ChatterWave...",
        downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
        downloadError: "Download falhou. Por favor, tente novamente.",
        features: "Por que ChatterWave?",
        featuresSub: "Tudo o que você precisa, nada que você não precisa",
        howItWorks: "Como Funciona",
        howItWorksSub: "Comece em 3 passos simples",
        privacy: "Sua Privacidade Importa",
        privacySub: "Acreditamos que suas conversas são seus negócios",
        ready: "Pronto para Simplificar Suas Mensagens?",
        readySub: "Junte-se a milhares de pessoas que simplificaram sua experiência de mensagens",
        downloadLarge: "Baixar ChatterWave",
        step1Title: "Baixe o Aplicativo",
        step1Desc: "Clique no botão de download para obter o arquivo APK ChatterWave.",
        step2Title: "Instale o APK",
        step2Desc: "Abra o arquivo baixado e siga as instruções de instalação.",
        step3Title: "Crie e Converse",
        step3Desc: "Escolha um nome de usuário, crie uma senha e comece a conversar instantaneamente!",
        installTip: "💡 Dica Pro: Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        installCompat: "📱 Compatível com Android 6.0 e superior",
        feat1Title: "Limpo e Bonito",
        feat1Desc: "Design moderno sem distrações, fácil nos olhos e simples de usar.",
        feat2Title: "Compartilhe Qualquer Coisa",
        feat2Desc: "Envie fotos, vídeos, documentos e mais. Sem limites no que você pode compartilhar.",
        feat3Title: "Chats Privados",
        feat3Desc: "Suas conversas ficam entre você e a pessoa com quem está falando.",
        feat4Title: "Ultra Rápido",
        feat4Desc: "As mensagens aparecem instantaneamente. Sem esperas, sem carregamento, apenas bate-papo perfeito.",
        feat5Title: "Funciona em Todo Lugar",
        feat5Desc: "Use no seu computador, tablet ou telefone. A mesma ótima experiência em todo lugar.",
        feat6Title: "Modo Escuro",
        feat6Desc: "Muda automaticamente para o modo escuro à noite. Fácil para os olhos e bateria.",
        feat7Title: "Histórico de Chat",
        feat7Desc: "Nunca perca uma conversa. Seus chats são salvos e organizados automaticamente.",
        feat8Title: "Seguro",
        feat8Desc: "Suas senhas são criptografadas com segurança. Sua privacidade é nossa principal prioridade.",
        feat9Title: "Sem Configuração Complicada",
        feat9Desc: "Apenas nome de usuário e senha. Você está pronto em 30 segundos. Nenhuma verificação de telefone necessária.",
        privacy1: "Mantém seus chats privados - apenas você e seu parceiro de conversa podem acessá-los",
        privacy2: "Criptografa sua senha com segurança",
        privacy3: "Não rastreia suas conversas",
        privacy4: "Não vende seus dados",
        privacy5: "Respeita sua privacidade",
        privacy6: "Sem anúncios, sem distrações",
        ctaNote1: "🌐 Não requer cartão de crédito • Sem taxas ocultas",
        ctaNote2: "📱 Funciona em todos os dispositivos • 🔒 Seguro e protegido",
        footerTitle: "ChatterWave",
        madeBy: "Mensagens simples, conexões reais",
        footerNote: "Feito com ❤️ para pessoas que apreciam a simplicidade"
    }
};

// Language names in native script
const languageNames = {
    en: "English",
    ar: "العربية",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    zh: "中文",
    hi: "हिन्दी",
    pt: "Português"
};

// RTL languages
const rtlLanguages = ['ar'];
