// Language translations for Watch Together (w2g)
const translations = {
    en: {
        title: "Watch Together",
        tagline: "Watch videos with friends and family in real-time",
        subtitle: "Sync • Chat • Enjoy Together",
        download: "Download App",
        explore: "Explore Features",
        screenshot: "View Screenshot",
        loading: "Loading...",
        downloading: "Downloading: Watch Together...",
        downloadStarted: "Download started! Check your downloads folder.",
        downloadError: "Download failed. Please try again.",
        features: "Powerful Features",
        featuresSub: "Everything you need for amazing watch parties",
        howItWorks: "How It Works",
        howItWorksSub: "Get started in 3 simple steps",
        safety: "Privacy First",
        safetySub: "Your privacy is our top priority",
        ready: "Ready to Watch Together?",
        readySub: "Join thousands of users watching videos with friends and family worldwide",
        downloadLarge: "Download Watch Together",
        webVersion: "Use Web Version",
        apkSize: "APK • 15 MB",
        free: "Free to use",
        noRegistration: "No registration required",
        allDevices: "Works on all devices",
        safe: "Safe & secure",
        step1Title: "Download the App",
        step1Desc: "Click the download button to get the Watch Together APK file.",
        step2Title: "Install the APK",
        step2Desc: "Open the downloaded file and follow the installation prompts.",
        step3Title: "Start Watching",
        step3Desc: "Create a room, invite friends, and enjoy synchronized video watching together!",
        proTip: "Pro Tip:",
        proTipDesc: "For easier installation, use a file manager app to locate and open the APK file.",
        compatible: "Compatible with Android 6.0 and above",
        visitSite: "Visit Website",
        faq: "FAQ",
        privacy: "Privacy Policy",
        footerNote: "This is a showcase page. Watch Together is a trademark of its respective owners.",
        madeBy: "The modern way to watch videos together online",
        statUsers: "Happy Users",
        statVideos: "Videos Watched",
        statSync: "Always Synced",
        feat1Title: "Sync Playback",
        feat1Desc: "Real-time synchronized video playback. Everyone watches at the exact same moment, no matter where they are.",
        feat2Title: "Live Chat",
        feat2Desc: "Built-in chat while watching. Share reactions, comments, and emojis in real-time with your friends.",
        feat3Title: "Multiple Platforms",
        feat3Desc: "Supports YouTube, Vimeo, and direct video links. Watch from almost any source together.",
        feat4Title: "Private Rooms",
        feat4Desc: "Create private watch rooms with passwords. Only invited people can join your viewing party.",
        feat5Title: "Instant Sync",
        feat5Desc: "Instant playback synchronization with minimal latency. Start watching together in seconds.",
        feat6Title: "Global Access",
        feat6Desc: "Connect with friends worldwide. Watch together regardless of geographic location or time zone.",
        feat7Title: "Custom Controls",
        feat7Desc: "Anyone can pause, play, or seek. All participants stay perfectly synchronized automatically.",
        feat8Title: "Themes & Emojis",
        feat8Desc: "Personalize your watch party with custom themes, emojis, and chat stickers for more fun.",
        feat9Title: "Mobile Friendly",
        feat9Desc: "Works perfectly on all devices. Watch together on phones, tablets, or computers seamlessly.",
        feat10Title: "Watch Parties",
        feat10Desc: "Host watch parties for movies, shows, or any video content. Perfect for long-distance friends and family.",
        feat11Title: "Unlimited Guests",
        feat11Desc: "Invite unlimited friends to your watch room. The more, the merrier for your viewing experience.",
        feat12Title: "HD Quality",
        feat12Desc: "Support for high-definition video streaming. Enjoy your content in the best quality available.",
        installTip: "💡 Pro Tip: For easier installation, use a file manager app to locate and open the APK file.",
        installCompat: "📱 Compatible with Android 6.0 and above",
        safety1: "End-to-end encryption for all chats",
        safety2: "No personal data required",
        safety3: "Private password-protected rooms",
        safety4: "No tracking or ads",
        safety5: "Open source and transparent",
        safety6: "Self-destructing room options",
        ctaNote1: "🌐 Free to use • No registration required",
        ctaNote2: "📱 Works on all devices • 🔒 Safe & secure",
        footerTitle: "Watch Together"
    },
    ar: {
        title: "شاهد معاً",
        tagline: "شاهد الفيديوهات مع الأصدقاء والعائلة في الوقت الفعلي",
        subtitle: "مزامنة • دردشة • استمتع معاً",
        download: "تحميل التطبيق",
        explore: "استكشف المميزات",
        screenshot: "عرض لقطة الشاشة",
        loading: "جاري التحميل...",
        downloading: "جاري التنزيل: شاهد معاً...",
        downloadStarted: "بدأ التنزيل! تحقق من مجلد التنزيلات.",
        downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
        features: "ميزات قوية",
        featuresSub: "كل ما تحتاجه لحفلات مشاهدة رائعة",
        howItWorks: "كيف يعمل",
        howItWorksSub: "ابدأ في 3 خطوات بسيطة",
        safety: "الخصوصية أولاً",
        safetySub: "خصوصيتك هي أولويتنا القصوى",
        ready: "مستعد للمشاهدة معاً؟",
        readySub: "انضم إلى آلاف المستخدمين الذين يشاهدون الفيديوهات مع الأصدقاء والعائلة حول العالم",
        downloadLarge: "تحميل شاهد معاً",
        webVersion: "استخدم النسخة الويب",
        apkSize: "APK • 15 ميجابايت",
        free: "استخدام مجاني",
        noRegistration: "لا يتطلب التسجيل",
        allDevices: "يعمل على جميع الأجهزة",
        safe: "آمن ومحمي",
        step1Title: "تحميل التطبيق",
        step1Desc: "انقر على زر التنزيل للحصول على ملف تطبيق شاهد معاً.",
        step2Title: "تثبيت التطبيق",
        step2Desc: "افتح الملف الذي تم تنزيله واتبع تعليمات التثبيت.",
        step3Title: "ابدأ المشاهدة",
        step3Desc: "أنشئ غرفة، أدعو الأصدقاء، واستمتع بمشاهدة الفيديوهات المتزامنة معاً!",
        proTip: "نصيحة:",
        proTipDesc: "لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        compatible: "متوافق مع Android 6.0 وما فوق",
        visitSite: "زيارة الموقع",
        faq: "الأسئلة الشائعة",
        privacy: "سياسة الخصوصية",
        footerNote: "هذه صفحة عرض. شاهد معاً هي علامة تجارية مملوكة لأصحابها.",
        madeBy: "الطريقة الحديثة لمشاهدة الفيديوهات معاً عبر الإنترنت",
        statUsers: "مستخدمون سعداء",
        statVideos: "فيديوهات تمت مشاهدتها",
        statSync: "دائماً متزامن",
        feat1Title: "مزامنة التشغيل",
        feat1Desc: "مزامنة التشغيل في الوقت الفعلي. الجميع يشاهد في نفس اللحظة بالضبط، بغض النظر عن موقعهم.",
        feat2Title: "دردشة مباشرة",
        feat2Desc: "دردشة مدمجة أثناء المشاهدة. شارك التفاعلات والتعليقات والرموز التعبيرية في الوقت الفعلي مع أصدقائك.",
        feat3Title: "منصات متعددة",
        feat3Desc: "يدعم YouTube و Vimeo والروابط المباشرة للفيديو. شاهد من أي مصدر تقريباً معاً.",
        feat4Title: "غرف خاصة",
        feat4Desc: "أنشئ غرف مشاهدة خاصة بكلمات مرور. فقط الأشخاص المدعوون يمكنهم الانضمام إلى حفلة المشاهدة.",
        feat5Title: "مزامنة فورية",
        feat5Desc: "مزامنة تشغيل فورية بزمن انتقال منخفض. ابدأ المشاهدة معاً في ثوانٍ.",
        feat6Title: "وصول عالمي",
        feat6Desc: "تواصل مع الأصدقاء في جميع أنحاء العالم. شاهد معاً بغض النظر عن الموقع الجغرافي أو المنطقة الزمنية.",
        feat7Title: "تحكمات مخصصة",
        feat7Desc: "يمكن لأي شخص إيقاف مؤقت أو تشغيل أو البحث. يبقى جميع المشاركين متزامنين بشكل مثالي تلقائياً.",
        feat8Title: "سمات ورموز تعبيرية",
        feat8Desc: "خصص حفلة المشاهدة الخاصة بك بسمات مخصصة ورموز تعبيرية وملصقات دردشة للمزيد من المتعة.",
        feat9Title: "متحرك الصديق",
        feat9Desc: "يعمل بشكل مثالي على جميع الأجهزة. شاهد معاً على الهواتف أو الأجهزة اللوحية أو أجهزة الكمبيوتر بسلاسة.",
        feat10Title: "حفلات المشاهدة",
        feat10Desc: "استضف حفلات مشاهدة للأفلام أو العروض أو أي محتوى فيديو. مثالي للأصدقاء والعائلة على مسافة بعيدة.",
        feat11Title: "ضيوف غير محدودين",
        feat11Desc: "ادعو أصدقاء غير محدودين إلى غرفة المشاهدة الخاصة بك. كلما زاد العدد، زادت المتعة لتجربة المشاهدة.",
        feat12Title: "جودة HD",
        feat12Desc: "دعم لدفق الفيديو عالي الدقة. استمتع بمحتواك بأفضل جودة متاحة.",
        installTip: "💡 نصيحة: لتسهيل التثبيت، استخدم تطبيق مدير الملفات لتحديد موقع وفتح ملف APK.",
        installCompat: "📱 متوافق مع Android 6.0 وما فوق",
        safety1: "تشفير من طرف إلى طرف لجميع الدردشات",
        safety2: "لا تتطلب بيانات شخصية",
        safety3: "غرف خاصة محمية بكلمة مرور",
        safety4: "لا تتبع أو إعلانات",
        safety5: "مفتوح المصدر وشفاف",
        safety6: "خيارات غرف ذاتية التدمير",
        ctaNote1: "🌐 مجاني الاستخدام • لا يتطلب تسجيل",
        ctaNote2: "📱 يعمل على جميع الأجهزة • 🔒 آمن ومحمي",
        footerTitle: "شاهد معاً"
    },
    es: {
        title: "Ver Juntos",
        tagline: "Mira videos con amigos y familia en tiempo real",
        subtitle: "Sincroniza • Chatea • Disfruta Juntos",
        download: "Descargar Aplicación",
        explore: "Explorar Características",
        screenshot: "Ver Captura",
        loading: "Cargando...",
        downloading: "Descargando: Ver Juntos...",
        downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
        downloadError: "Descarga fallida. Por favor, inténtalo de nuevo.",
        features: "Características Potentes",
        featuresSub: "Todo lo que necesitas para amazing watch parties",
        howItWorks: "Cómo Funciona",
        howItWorksSub: "Comienza en 3 simples pasos",
        safety: "Privacidad Primero",
        safetySub: "Tu privacidad es nuestra prioridad",
        ready: "¿Listo para Ver Juntos?",
        readySub: "Únete a miles de usuarios viendo videos con amigos y familia en todo el mundo",
        downloadLarge: "Descargar Ver Juntos",
        webVersion: "Usar Versión Web",
        apkSize: "APK • 15 MB",
        free: "Gratis para usar",
        noRegistration: "Sin registro requerido",
        allDevices: "Funciona en todos los dispositivos",
        safe: "Seguro y protegido",
        step1Title: "Descarga la Aplicación",
        step1Desc: "Haz clic en el botón de descarga para obtener el archivo APK de Ver Juntos.",
        step2Title: "Instala el APK",
        step2Desc: "Abre el archivo descargado y sigue las instrucciones de instalación.",
        step3Title: "Empieza a Ver",
        step3Desc: "¡Crea una sala, invita amigos y disfruta de videos sincronizados juntos!",
        proTip: "Consejo Pro:",
        proTipDesc: "Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        compatible: "Compatible con Android 6.0 y superior",
        visitSite: "Visitar Sitio Web",
        faq: "Preguntas Frecuentes",
        privacy: "Política de Privacidad",
        footerNote: "Esta es una página de demostración. Ver Juntos es una marca comercial de sus respectivos propietarios.",
        madeBy: "La forma moderna de ver videos juntos en línea",
        statUsers: "Usuarios Felices",
        statVideos: "Videos Vistos",
        statSync: "Siempre Sincronizado",
        feat1Title: "Reproducción Sincronizada",
        feat1Desc: "Reproducción sincronizada en tiempo real. Todos ven en el mismo momento exacto, sin importar dónde estén.",
        feat2Title: "Chat en Vivo",
        feat2Desc: "Chat integrado mientras miras. Comparte reacciones, comentarios y emojis en tiempo real con tus amigos.",
        feat3Title: "Múltiples Plataformas",
        feat3Desc: "Soporta YouTube, Vimeo y enlaces directos de video. Mira desde casi cualquier fuente juntos.",
        feat4Title: "Salas Privadas",
        feat4Desc: "Crea salas de visualización privadas con contraseñas. Solo las personas invitadas pueden unirse a tu fiesta de visualización.",
        feat5Title: "Sincronización Instantánea",
        feat5Desc: "Sincronización de reproducción instantánea con latencia mínima. Comienza a ver juntos en segundos.",
        feat6Title: "Acceso Global",
        feat6Desc: "Conéctate con amigos en todo el mundo. Mira juntos sin importar la ubicación geográfica o la zona horaria.",
        feat7Title: "Controles Personalizados",
        feat7Desc: "Cualquiera puede pausar, reproducir o buscar. Todos los participantes se mantienen perfectamente sincronizados automáticamente.",
        feat8Title: "Temas y Emojis",
        feat8Desc: "Personaliza tu fiesta de visualización con temas personalizados, emojis y pegatinas de chat para más diversión.",
        feat9Title: "Amigable con Móviles",
        feat9Desc: "Funciona perfectamente en todos los dispositivos. Mira juntos en teléfonos, tabletas o computadoras sin problemas.",
        feat10Title: "Fiestas de Visualización",
        feat10Desc: "Organiza fiestas de visualización para películas, programas o cualquier contenido de video. Perfecto para amigos y familiares a distancia.",
        feat11Title: "Invitados Ilimitados",
        feat11Desc: "Invita amigos ilimitados a tu sala de visualización. Cuanto más, mejor para tu experiencia de visualización.",
        feat12Title: "Calidad HD",
        feat12Desc: "Soporte para transmisión de video de alta definición. Disfruta tu contenido en la mejor calidad disponible.",
        installTip: "💡 Consejo Pro: Para una instalación más fácil, usa un administrador de archivos para ubicar y abrir el archivo APK.",
        installCompat: "📱 Compatible con Android 6.0 y superior",
        safety1: "Cifrado de extremo a extremo para todos los chats",
        safety2: "No se requieren datos personales",
        safety3: "Salas privadas protegidas con contraseña",
        safety4: "Sin rastreo ni anuncios",
        safety5: "Código abierto y transparente",
        safety6: "Opciones de salas autodestructivas",
        ctaNote1: "🌐 Gratis para usar • Sin registro requerido",
        ctaNote2: "📱 Funciona en todos los dispositivos • 🔒 Seguro y protegido",
        footerTitle: "Ver Juntos"
    },
    fr: {
        title: "Regarder Ensemble",
        tagline: "Regardez des vidéos avec amis et famille en temps réel",
        subtitle: "Synchroniser • Chat • Profiter Ensemble",
        download: "Télécharger l'Application",
        explore: "Explorer les Fonctionnalités",
        screenshot: "Voir Capture",
        loading: "Chargement...",
        downloading: "Téléchargement: Regarder Ensemble...",
        downloadStarted: "Téléchargement commencé! Vérifiez votre dossier de téléchargement.",
        downloadError: "Échec du téléchargement. Veuillez réessayer.",
        features: "Fonctionnalités Puissantes",
        featuresSub: "Tout ce dont vous avez besoin pour amazing watch parties",
        howItWorks: "Comment Ça Marche",
        howItWorksSub: "Commencez en 3 étapes simples",
        safety: "Confidentialité d'Abord",
        safetySub: "Votre confidentialité est notre priorité",
        ready: "Prêt à Regarder Ensemble?",
        readySub: "Rejoignez des milliers d'utilisateurs regardant des vidéos avec amis et famille dans le monde entier",
        downloadLarge: "Télécharger Regarder Ensemble",
        webVersion: "Version Web",
        apkSize: "APK • 15 MB",
        free: "Gratuit à utiliser",
        noRegistration: "Aucune inscription requise",
        allDevices: "Fonctionne sur tous les appareils",
        safe: "Sûr et sécurisé",
        step1Title: "Télécharger l'Application",
        step1Desc: "Cliquez sur le bouton de téléchargement pour obtenir le fichier APK Regarder Ensemble.",
        step2Title: "Installer l'APK",
        step2Desc: "Ouvrez le fichier téléchargé et suivez les instructions d'installation.",
        step3Title: "Commencer à Regarder",
        step3Desc: "Créez une salle, invitez des amis et profitez de vidéos synchronisées ensemble!",
        proTip: "Conseil Pro:",
        proTipDesc: "Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        compatible: "Compatible avec Android 6.0 et supérieur",
        visitSite: "Visiter le Site",
        faq: "FAQ",
        privacy: "Politique de Confidentialité",
        footerNote: "Ceci est une page de démonstration. Regarder Ensemble est une marque commerciale de ses propriétaires respectifs.",
        madeBy: "La façon moderne de regarder des vidéos ensemble en ligne",
        statUsers: "Utilisateurs Heureux",
        statVideos: "Vidéos Regardées",
        statSync: "Toujours Synchronisé",
        feat1Title: "Lecture Synchronisée",
        feat1Desc: "Lecture synchronisée en temps réel. Tout le monde regarde au même moment exact, peu importe où ils sont.",
        feat2Title: "Chat en Direct",
        feat2Desc: "Chat intégré pendant le visionnage. Partagez des réactions, des commentaires et des emojis en temps réel avec vos amis.",
        feat3Title: "Plateformes Multiples",
        feat3Desc: "Prend en charge YouTube, Vimeo et les liens vidéo directs. Regardez depuis presque n'importe quelle source ensemble.",
        feat4Title: "Salles Privées",
        feat4Desc: "Créez des salles de visualisation privées avec des mots de passe. Seules les personnes invitées peuvent rejoindre votre soirée de visualisation.",
        feat5Title: "Synchronisation Instantanée",
        feat5Desc: "Synchronisation de lecture instantanée avec une latence minimale. Commencez à regarder ensemble en quelques secondes.",
        feat6Title: "Accès Mondial",
        feat6Desc: "Connectez-vous avec des amis du monde entier. Regardez ensemble indépendamment de la situation géographique ou du fuseau horaire.",
        feat7Title: "Contrôles Personnalisés",
        feat7Desc: "N'importe qui peut mettre en pause, lire ou rechercher. Tous les participants restent parfaitement synchronisés automatiquement.",
        feat8Title: "Thèmes et Emojis",
        feat8Desc: "Personnalisez votre soirée de visualisation avec des thèmes personnalisés, des emojis et des autocollants de chat pour plus de plaisir.",
        feat9Title: "Compatible Mobile",
        feat9Desc: "Fonctionne parfaitement sur tous les appareils. Regardez ensemble sur téléphones, tablettes ou ordinateurs sans problème.",
        feat10Title: "Soirées de Visualisation",
        feat10Desc: "Organisez des soirées de visualisation pour des films, des émissions ou n'importe quel contenu vidéo. Parfait pour les amis et la famille à distance.",
        feat11Title: "Invités Illimités",
        feat11Desc: "Invitez des amis illimités dans votre salle de visualisation. Plus c'est, plus c'est amusant pour votre expérience de visualisation.",
        feat12Title: "Qualité HD",
        feat12Desc: "Prise en charge du streaming vidéo haute définition. Profitez de votre contenu dans la meilleure qualité disponible.",
        installTip: "💡 Conseil Pro: Pour une installation plus facile, utilisez un gestionnaire de fichiers pour localiser et ouvrir le fichier APK.",
        installCompat: "📱 Compatible avec Android 6.0 et supérieur",
        safety1: "Chiffrement de bout en bout pour tous les chats",
        safety2: "Aucune donnée personnelle requise",
        safety3: "Salles privées protégées par mot de passe",
        safety4: "Pas de suivi ou de publicités",
        safety5: "Open source et transparent",
        safety6: "Options de salles autodestructrices",
        ctaNote1: "🌐 Gratuit à utiliser • Aucune inscription requise",
        ctaNote2: "📱 Fonctionne sur tous les appareils • 🔒 Sûr et sécurisé",
        footerTitle: "Regarder Ensemble"
    },
    de: {
        title: "Zusammen Schauen",
        tagline: "Videos mit Freunden und Familie in Echtzeit ansehen",
        subtitle: "Synchronisieren • Chatten • Zusammen Genießen",
        download: "App Herunterladen",
        explore: "Funktionen Erkunden",
        screenshot: "Screenshot Anzeigen",
        loading: "Laden...",
        downloading: "Herunterladen: Zusammen Schauen...",
        downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
        downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
        features: "Leistungsstarke Funktionen",
        featuresSub: "Alles was Sie für amazing watch parties brauchen",
        howItWorks: "So Funktionierts",
        howItWorksSub: "Starten Sie in 3 einfachen Schritten",
        safety: "Privatsphäre Zuerst",
        safetySub: "Ihre Privatsphäre ist unsere Priorität",
        ready: "Bereit Zusammen zu Schauen?",
        readySub: "Schließen Sie sich Tausenden von Benutzern an, die mit Freunden und Familie weltweit Videos ansehen",
        downloadLarge: "Zusammen Schauen Herunterladen",
        webVersion: "Web-Version Nutzen",
        apkSize: "APK • 15 MB",
        free: "Kostenlos Nutzen",
        noRegistration: "Keine Registrierung Erforderlich",
        allDevices: "Funktioniert Auf Allen Geräten",
        safe: "Sicher & Geschützt",
        step1Title: "App Herunterladen",
        step1Desc: "Klicken Sie auf den Download-Button, um die Zusammen Schauen APK-Datei zu erhalten.",
        step2Title: "APK Installieren",
        step2Desc: "Öffnen Sie die heruntergeladene Datei und folgen Sie den Installationsanweisungen.",
        step3Title: "Anfangen zu Schauen",
        step3Desc: "Erstellen Sie einen Raum, laden Sie Freunde ein und genießen Sie synchronisiertes Videoansehen zusammen!",
        proTip: "Pro-Tipp:",
        proTipDesc: "Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        compatible: "Kompatibel mit Android 6.0 und höher",
        visitSite: "Webseite Besuchen",
        faq: "FAQ",
        privacy: "Datenschutzerklärung",
        footerNote: "Dies ist eine Demo-Seite. Zusammen Schauen ist eine Marke der jeweiligen Eigentümer.",
        madeBy: "Die moderne Art, Videos zusammen online anzusehen",
        statUsers: "Zufriedene Benutzer",
        statVideos: "Videos Gesehen",
        statSync: "Immer Synchronisiert",
        feat1Title: "Sync-Wiedergabe",
        feat1Desc: "Echtzeit-synchronisierte Videowiedergabe. Alle schauen zur gleichen Zeit, egal wo sie sind.",
        feat2Title: "Live-Chat",
        feat2Desc: "Integrierter Chat beim Ansehen. Teilen Sie Reaktionen, Kommentare und Emojis in Echtzeit mit Freunden.",
        feat3Title: "Mehrere Plattformen",
        feat3Desc: "Unterstützt YouTube, Vimeo und direkte Video-Links. Schauen Sie aus fast jeder Quelle zusammen.",
        feat4Title: "Private Räume",
        feat4Desc: "Erstellen Sie private Zuschauerräume mit Passwörtern. Nur eingeladene Personen können Ihrer Viewing-Party beitreten.",
        feat5Title: "Sofortige Synchronisation",
        feat5Desc: "Sofortige Wiedergabesynchronisation mit minimaler Latenz. Fangen Sie in Sekunden an zusammen zu schauen.",
        feat6Title: "Globaler Zugang",
        feat6Desc: "Verbinden Sie sich mit Freunden weltweit. Schauen Sie zusammen unabhängig von geografischer Lage oder Zeitzone.",
        feat7Title: "Benutzerdefinierte Steuerungen",
        feat7Desc: "Jeder kann pausieren, abspielen oder suchen. Alle Teilnehmer bleiben automatisch perfekt synchronisiert.",
        feat8Title: "Themen & Emojis",
        feat8Desc: "Personalisieren Sie Ihre Viewing-Party mit benutzerdefinierten Themen, Emojis und Chat-Aufklebern für mehr Spaß.",
        feat9Title: "Mobil-freundlich",
        feat9Desc: "Funktioniert perfekt auf allen Geräten. Schauen Sie zusammen auf Telefonen, Tablets oder Computern nahtlos.",
        feat10Title: "Viewing-Partys",
        feat10Desc: "Hosten Sie Viewing-Partys für Filme, Shows oder Video-Inhalte. Perfekt für Freunde und Familie aus der Ferne.",
        feat11Title: "Unbegrenzte Gäste",
        feat11Desc: "Laden Sie unbegrenzte Freunde in Ihren Zuschauerraum ein. Je mehr, desto besser für Ihr Seherlebnis.",
        feat12Title: "HD-Qualität",
        feat12Desc: "Unterstützung für High-Definition-Video-Streaming. Genießen Sie Ihre Inhalte in der besten verfügbaren Qualität.",
        installTip: "💡 Pro-Tipp: Für eine einfachere Installation verwenden Sie einen Dateimanager, um die APK-Datei zu finden und zu öffnen.",
        installCompat: "📱 Kompatibel mit Android 6.0 und höher",
        safety1: "Ende-zu-Ende-Verschlüsselung für alle Chats",
        safety2: "Keine persönlichen Daten erforderlich",
        safety3: "Private passwortgeschützte Räume",
        safety4: "Kein Tracking oder Werbung",
        safety5: "Open Source und transparent",
        safety6: "Optionen für selbstzerstörende Räume",
        ctaNote1: "🌐 Kostenlos nutzen • Keine Registrierung erforderlich",
        ctaNote2: "📱 Funktioniert auf allen Geräten • 🔒 Sicher & geschützt",
        footerTitle: "Zusammen Schauen"
    },
    zh: {
        title: "一起观看",
        tagline: "与朋友和家人实时观看视频",
        subtitle: "同步 • 聊天 • 一起享受",
        download: "下载应用",
        explore: "探索功能",
        screenshot: "查看截图",
        loading: "加载中...",
        downloading: "正在下载: 一起观看...",
        downloadStarted: "下载已开始！请检查您的下载文件夹。",
        downloadError: "下载失败。请重试。",
        features: "强大功能",
        featuresSub: "精彩观看派对所需的一切",
        howItWorks: "如何使用",
        howItWorksSub: "3 个简单步骤开始",
        safety: "隐私第一",
        safetySub: "您的隐私是我们的首要任务",
        ready: "准备一起观看吗？",
        readySub: "加入全球数千名与朋友和家人一起观看视频的用户",
        downloadLarge: "下载一起观看",
        webVersion: "使用网页版",
        apkSize: "APK • 15 MB",
        free: "免费使用",
        noRegistration: "无需注册",
        allDevices: "适用于所有设备",
        safe: "安全可靠",
        step1Title: "下载应用",
        step1Desc: "点击下载按钮获取一起观看 APK 文件。",
        step2Title: "安装 APK",
        step2Desc: "打开下载的文件并按照安装提示操作。",
        step3Title: "开始观看",
        step3Desc: "创建房间，邀请朋友，一起享受同步视频观看！",
        proTip: "专业提示:",
        proTipDesc: "为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        compatible: "兼容 Android 6.0 及更高版本",
        visitSite: "访问网站",
        faq: "常见问题",
        privacy: "隐私政策",
        footerNote: "这是一个展示页面。一起观看是其各自所有者的商标。",
        madeBy: "在线一起观看视频的现代方式",
        statUsers: "满意用户",
        statVideos: "观看视频",
        statSync: "始终同步",
        feat1Title: "同步播放",
        feat1Desc: "实时同步视频播放。无论身在何处，所有人都在同一时刻观看。",
        feat2Title: "实时聊天",
        feat2Desc: "观看时内置聊天。与朋友实时分享反应、评论和表情符号。",
        feat3Title: "多平台支持",
        feat3Desc: "支持 YouTube、Vimeo 和直接视频链接。几乎可以从任何来源一起观看。",
        feat4Title: "私人房间",
        feat4Desc: "创建带密码的私人观看房间。只有受邀人员可以加入您的观看派对。",
        feat5Title: "即时同步",
        feat5Desc: "即时播放同步，延迟极低。在几秒钟内开始一起观看。",
        feat6Title: "全球访问",
        feat6Desc: "与全球朋友联系。无论地理位置或时区如何，都可以一起观看。",
        feat7Title: "自定义控制",
        feat7Desc: "任何人都可以暂停、播放或搜索。所有参与者自动保持完美同步。",
        feat8Title: "主题和表情",
        feat8Desc: "使用自定义主题、表情和聊天贴纸个性化您的观看派对，增加更多乐趣。",
        feat9Title: "移动友好",
        feat9Desc: "在所有设备上完美运行。在手机、平板电脑或电脑上无缝一起观看。",
        feat10Title: "观看派对",
        feat10Desc: "为电影、节目或任何视频内容举办观看派对。非常适合异地朋友和家人。",
        feat11Title: "无限客人",
        feat11Desc: "邀请无限朋友加入您的观看房间。人越多，观看体验越好。",
        feat12Title: "高清质量",
        feat12Desc: "支持高清视频流媒体。以最佳质量享受您的内容。",
        installTip: "💡 专业提示：为了更轻松地安装，使用文件管理器应用找到并打开 APK 文件。",
        installCompat: "📱 兼容 Android 6.0 及更高版本",
        safety1: "所有聊天端到端加密",
        safety2: "不需要个人数据",
        safety3: "私人密码保护的房间",
        safety4: "无跟踪或广告",
        safety5: "开源和透明",
        safety6: "自毁房间选项",
        ctaNote1: "🌐 免费使用 • 无需注册",
        ctaNote2: "📱 适用于所有设备 • 🔒 安全可靠",
        footerTitle: "一起观看"
    },
    hi: {
        title: "साथ देखें",
        tagline: "दोस्तों और परिवार के साथ रियल-टाइम में वीडियो देखें",
        subtitle: "सिंक • चैट • साथ में आनंद लें",
        download: "ऐप डाउनलोड करें",
        explore: "सुविधाएं देखें",
        screenshot: "स्क्रीनशॉट देखें",
        loading: "लोड हो रहा है...",
        downloading: "डाउनलोड हो रहा है: साथ देखें...",
        downloadStarted: "डाउनलोड शुरू हो गया! अपने डाउनलोड फ़ोल्डर की जांच करें।",
        downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
        features: "शक्तिशाली सुविधाएं",
        featuresSub: "शानदार वॉच पार्टियों के लिए आपको जो भी चाहिए",
        howItWorks: "यह कैसे काम करता है",
        howItWorksSub: "3 सरल चरणों में शुरू करें",
        safety: "गोपनीयता पहले",
        safetySub: "आपकी गोपनीयता हमारी प्राथमिकता है",
        ready: "साथ देखने के लिए तैयार हैं?",
        readySub: "दोस्तों और परिवार के साथ वीडियो देखने वाले हजारों उपयोगकर्ताओं से जुड़ें",
        downloadLarge: "साथ देखें डाउनलोड करें",
        webVersion: "वेब संस्करण का प्रयोग करें",
        apkSize: "APK • 15 MB",
        free: "मुफ्त में उपयोग करें",
        noRegistration: "पंजीकरण की आवश्यकता नहीं",
        allDevices: "सभी उपकरणों पर काम करता है",
        safe: "सुरक्षित और सुरक्षित",
        step1Title: "ऐप डाउनलोड करें",
        step1Desc: "साथ देखें APK फ़ाइल प्राप्त करने के लिए डाउनलोड बटन पर क्लिक करें।",
        step2Title: "APK इंस्टॉल करें",
        step2Desc: "डाउनलोड की गई फ़ाइल खोलें और इंस्टॉलेशन निर्देशों का पालन करें।",
        step3Title: "देखना शुरू करें",
        step3Desc: "एक रूम बनाएं, दोस्तों को आमंत्रित करें, और सिंक्रनाइज़्ड वीडियो देखने का आनंद लें!",
        proTip: "प्रो टिप:",
        proTipDesc: "आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        compatible: "Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        visitSite: "वेबसाइट पर जाएं",
        faq: "अक्सर पूछे जाने वाले प्रश्न",
        privacy: "गोपनीयता नीति",
        footerNote: "यह एक प्रदर्शन पृष्ठ है। साथ देखें अपने संबंधित मालिकों का एक ट्रेडमार्क है।",
        madeBy: "ऑनलाइन एक साथ वीडियो देखने का आधुनिक तरीका",
        statUsers: "खुश उपयोगकर्ता",
        statVideos: "देखे गए वीडियो",
        statSync: "हमेशा सिंक्रनाइज़्ड",
        feat1Title: "सिंक प्लेबैक",
        feat1Desc: "रियल-टाइम सिंक्रनाइज़्ड वीडियो प्लेबैक। सभी एक ही समय पर देखते हैं, चाहे वे कहीं भी हों।",
        feat2Title: "लाइव चैट",
        feat2Desc: "देखते समय बिल्ट-इन चैट। दोस्तों के साथ रियल-टाइम में प्रतिक्रियाएं, टिप्पणियां और इमोजी साझा करें।",
        feat3Title: "कई प्लेटफॉर्म",
        feat3Desc: "YouTube, Vimeo और प्रत्यक्ष वीडियो लिंक का समर्थन करता है। लगभग किसी भी स्रोत से एक साथ देखें।",
        feat4Title: "निजी कमरे",
        feat4Desc: "पासवर्ड के साथ निजी वॉच रूम बनाएं। केवल आमंत्रित लोग आपकी वॉच पार्टी में शामिल हो सकते हैं।",
        feat5Title: "त्वरित सिंक",
        feat5Desc: "न्यूनतम विलंब के साथ त्वरित प्लेबैक सिंक्रनाइज़ेशन। सेकंड में एक साथ देखना शुरू करें।",
        feat6Title: "वैश्विक पहुंच",
        feat6Desc: "दुनिया भर के दोस्तों से जुड़ें। भौगोलिक स्थान या समय क्षेत्र की परवाह किए बिना एक साथ देखें।",
        feat7Title: "कस्टम नियंत्रण",
        feat7Desc: "कोई भी रोक सकता है, चला सकता है या खोज सकता है। सभी प्रतिभागी स्वचालित रूप से पूरी तरह से सिंक्रनाइज़्ड रहते हैं।",
        feat8Title: "थीम और इमोजी",
        feat8Desc: "अधिक मज़े के लिए कस्टम थीम, इमोजी और चैट स्टिकर के साथ अपनी वॉच पार्टी को वैयक्तिकृत करें।",
        feat9Title: "मोबाइल के अनुकूल",
        feat9Desc: "सभी डिवाइस पर बेहतरीन ढंग से काम करता है। फोन, टैबलेट या कंप्यूटर पर बिना किसी समस्या के एक साथ देखें।",
        feat10Title: "वॉच पार्टियां",
        feat10Desc: "फिल्मों, शो या किसी भी वीडियो सामग्री के लिए वॉच पार्टियों की मेजबानी करें। लंबी दूरी के दोस्तों और परिवार के लिए बेहतरीन।",
        feat11Title: "असीमित मेहमान",
        feat11Desc: "अपने वॉच रूम में असीमित दोस्तों को आमंत्रित करें। आपके देखने के अनुभव के लिए जितना अधिक, उतना बेहतर।",
        feat12Title: "HD गुणवत्ता",
        feat12Desc: "हाई-डेफिनिशन वीडियो स्ट्रीमिंग के लिए समर्थन। अपनी सामग्री को सर्वोत्तम गुणवत्ता में आनंद लें।",
        installTip: "💡 प्रो टिप: आसान इंस्टॉलेशन के लिए, APK फ़ाइल को खोजने और खोलने के लिए फ़ाइल मैनेजर ऐप का उपयोग करें।",
        installCompat: "📱 Android 6.0 और उसके बाद के संस्करण के साथ संगत",
        safety1: "सभी चैट के लिए एंड-टू-एंड एन्क्रिप्शन",
        safety2: "कोई व्यक्तिगत डेटा आवश्यक नहीं",
        safety3: "निजी पासवर्ड-संरक्षित कमरे",
        safety4: "कोई ट्रैकिंग या विज्ञापन नहीं",
        safety5: "ओपन सोर्स और पारदर्शी",
        safety6: "स्व-विनाशक कमरे विकल्प",
        ctaNote1: "🌐 मुफ्त में उपयोग करें • पंजीकरण की आवश्यकता नहीं",
        ctaNote2: "📱 सभी उपकरणों पर काम करता है • 🔒 सुरक्षित और सुरक्षित",
        footerTitle: "साथ देखें"
    },
    pt: {
        title: "Assistir Juntos",
        tagline: "Assista a vídeos com amigos e família em tempo real",
        subtitle: "Sincronizar • Chat • Desfrutar Juntos",
        download: "Baixar Aplicativo",
        explore: "Explorar Recursos",
        screenshot: "Ver Captura",
        loading: "Carregando...",
        downloading: "Baixando: Assistir Juntos...",
        downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
        downloadError: "Download falhou. Por favor, tente novamente.",
        features: "Recursos Poderosos",
        featuresSub: "Tudo o que você precisa para amazing watch parties",
        howItWorks: "Como Funciona",
        howItWorksSub: "Comece em 3 passos simples",
        safety: "Privacidade Primeiro",
        safetySub: "Sua privacidade é nossa prioridade",
        ready: "Pronto para Assistir Juntos?",
        readySub: "Junte-se a milhares de usuários assistindo a vídeos com amigos e família em todo o mundo",
        downloadLarge: "Baixar Assistir Juntos",
        webVersion: "Usar Versão Web",
        apkSize: "APK • 15 MB",
        free: "Gratuito para usar",
        noRegistration: "Sem registro necessário",
        allDevices: "Funciona em todos os dispositivos",
        safe: "Seguro e protegido",
        step1Title: "Baixe o Aplicativo",
        step1Desc: "Clique no botão de download para obter o arquivo APK Assistir Juntos.",
        step2Title: "Instale o APK",
        step2Desc: "Abra o arquivo baixado e siga as instruções de instalação.",
        step3Title: "Comece a Assistir",
        step3Desc: "Crie uma sala, convide amigos e desfrute de vídeos sincronizados juntos!",
        proTip: "Dica Pro:",
        proTipDesc: "Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        compatible: "Compatível com Android 6.0 e superior",
        visitSite: "Visitar Site",
        faq: "Perguntas Frequentes",
        privacy: "Política de Privacidade",
        footerNote: "Esta é uma página de demonstração. Assistir Juntos é uma marca comercial de seus respectivos proprietários.",
        madeBy: "A forma moderna de assistir vídeos juntos online",
        statUsers: "Usuários Felizes",
        statVideos: "Vídeos Assistidos",
        statSync: "Sempre Sincronizado",
        feat1Title: "Reprodução Sincronizada",
        feat1Desc: "Reprodução de vídeo sincronizada em tempo real. Todos assistem no mesmo momento exato, não importa onde estejam.",
        feat2Title: "Chat Ao Vivo",
        feat2Desc: "Chat integrado durante a exibição. Compartilhe reações, comentários e emojis em tempo real com seus amigos.",
        feat3Title: "Múltiplas Plataformas",
        feat3Desc: "Suporta YouTube, Vimeo e links diretos de vídeo. Assista de quase qualquer fonte juntos.",
        feat4Title: "Salas Privadas",
        feat4Desc: "Crie salas de exibição privadas com senhas. Apenas pessoas convidadas podem participar da sua festa de exibição.",
        feat5Title: "Sincronização Instantânea",
        feat5Desc: "Sincronização de reprodução instantânea com latência mínima. Comece a assistir juntos em segundos.",
        feat6Title: "Acesso Global",
        feat6Desc: "Conecte-se com amigos em todo o mundo. Assista juntos independentemente da localização geográfica ou fuso horário.",
        feat7Title: "Controles Personalizados",
        feat7Desc: "Qualquer um pode pausar, reproduzir ou buscar. Todos os participantes permanecem perfeitamente sincronizados automaticamente.",
        feat8Title: "Temas e Emojis",
        feat8Desc: "Personalize sua festa de exibição com temas personalizados, emojis e adesivos de chat para mais diversão.",
        feat9Title: "Amigável para Mobile",
        feat9Desc: "Funciona perfeitamente em todos os dispositivos. Assista juntos em telefones, tablets ou computadores sem problemas.",
        feat10Title: "Festas de Exibição",
        feat10Desc: "Hospede festas de exibição para filmes, programas ou qualquer conteúdo de vídeo. Perfeito para amigos e família à distância.",
        feat11Title: "Convidados Ilimitados",
        feat11Desc: "Convide amigos ilimitados para sua sala de exibição. Quanto mais, melhor para sua experiência de exibição.",
        feat12Title: "Qualidade HD",
        feat12Desc: "Suporte para streaming de vídeo em alta definição. Desfrute seu conteúdo na melhor qualidade disponível.",
        installTip: "💡 Dica Pro: Para uma instalação mais fácil, use um gerenciador de arquivos para localizar e abrir o arquivo APK.",
        installCompat: "📱 Compatível com Android 6.0 e superior",
        safety1: "Criptografia de ponta a ponta para todos os chats",
        safety2: "Nenhum dado pessoal necessário",
        safety3: "Salas privadas protegidas por senha",
        safety4: "Sem rastreamento ou anúncios",
        safety5: "Código aberto e transparente",
        safety6: "Opções de sala autodestrutiva",
        ctaNote1: "🌐 Gratuito para usar • Sem registro necessário",
        ctaNote2: "📱 Funciona em todos os dispositivos • 🔒 Seguro e protegido",
        footerTitle: "Assistir Juntos"
    }
};

// Language names in native script
const languageNames = {
    en: "English",
    ar: "العربية",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    zh: "中文",
    hi: "हिन्दी",
    pt: "Português"
};

// RTL languages
const rtlLanguages = ['ar'];
